const DB = {
    weapons: [
        // --- SOMBER WEAPONS (UNIQUE) ---
        { id: 'rob', name: "Rivers of Blood", type: 'Somber', bleed: true, dmg: 'Slash/Fire', skill: "Corpse Piler", stats:['dex','arc'], scale: {d:'B', a:'D'}, buffable: false, loc: "Mountaintops (Church of Repose)" },
        { id: 'moon', name: "Moonveil", type: 'Somber', bleed: true, dmg: 'Slash/Magic', skill: "Transient Moonlight", stats:['dex','int'], scale: {d:'B', i:'B'}, buffable: false, loc: "Caelid (Gael Tunnel)" },
        { id: 'blas', name: "Blasphemous Blade", type: 'Somber', bleed: false, dmg: 'Standard/Fire', skill: "Taker's Flames", stats:['str','fai'], scale: {s:'C', f:'B'}, buffable: false, loc: "Volcano Manor (Rykard Rem.)" },
        { id: 'dark', name: "Dark Moon Greatsword", type: 'Somber', bleed: false, dmg: 'Standard/Magic', skill: "Moonlight Greatsword", stats:['int','str'], scale: {i:'B'}, buffable: false, loc: "Liurnia (Ranni Quest)" },
        { id: 'relic', name: "Sacred Relic Sword", type: 'Somber', bleed: false, dmg: 'Standard/Holy', skill: "Wave of Gold", stats:['dex','fai'], scale: {d:'B', f:'C'}, buffable: false, loc: "Elden Beast Remembrance" },
        { id: 'ruins', name: "Ruins Greatsword", type: 'Somber', bleed: false, dmg: 'Standard/Magic', skill: "Wave of Destruction", stats:['str'], scale: {s:'S'}, buffable: false, loc: "Redmane Castle Plaza" },
        { id: 'bolt', name: "Bolt of Gransax", type: 'Somber', bleed: false, dmg: 'Pierce/Lightning', skill: "Ancient Lightning Spear", stats:['dex'], scale: {d:'B'}, buffable: false, loc: "Leyndell Capital" },
        { id: 'fang', name: "Bloodhound's Fang", type: 'Somber', bleed: true, dmg: 'Slash', skill: "Bloodhound's Finesse", stats:['dex','str'], scale: {d:'B', s:'C'}, buffable: true, loc: "Limgrave (Forlorn Hound Evergaol)" },
        { id: 'mohg', name: "Mohgwyn's Spear", type: 'Somber', bleed: true, dmg: 'Pierce/Fire', skill: "Bloodboon Ritual", stats:['str','arc'], scale: {a:'C', s:'C'}, buffable: false, loc: "Mohgwyn Palace (Mohg Rem.)" },
        { id: 'morgott', name: "Morgott's Cursed Sword", type: 'Somber', bleed: true, dmg: 'Slash/Fire', skill: "Cursed-Blood Slice", stats:['dex','arc'], scale: {d:'B', a:'D'}, buffable: false, loc: "Leyndell (Morgott Rem.)" },
        { id: 'godslayer', name: "Godslayer's Greatsword", type: 'Somber', bleed: false, dmg: 'Standard/Fire', skill: "Queen's Black Flame", stats:['dex','fai'], scale: {d:'B', f:'C'}, buffable: false, loc: "Caelid (Divine Tower)" },
        { id: 'maliketh_b', name: "Maliketh's Black Blade", type: 'Somber', bleed: false, dmg: 'Standard/Holy', skill: "Destined Death", stats:['str','fai'], scale: {s:'B', f:'B'}, buffable: false, loc: "Farum Azula (Maliketh Rem.)" },
        { id: 'ordovis', name: "Ordovis's Greatsword", type: 'Somber', bleed: false, dmg: 'Standard/Holy', skill: "Ordovis's Vortex", stats:['str','fai'], scale: {s:'A', f:'C'}, buffable: false, loc: "Altus (Auriza Hero's Grave)" },
        { id: 'marais', name: "Marais Executioner's", type: 'Somber', bleed: false, dmg: 'Standard/Magic', skill: "Eochaid's Dancing Blade", stats:['str','arc'], scale: {s:'B', a:'D'}, buffable: false, loc: "Shaded Castle Boss" },
        { id: 'black_knife', name: "Black Knife", type: 'Somber', bleed: false, dmg: 'Slash/Holy', skill: "Blade of Death", stats:['dex','fai'], scale: {f:'B'}, buffable: false, loc: "Altus (Sainted Hero's Grave)" },
        { id: 'vyke', name: "Vyke's War Spear", type: 'Somber', bleed: false, dmg: 'Pierce/Fire', skill: "Frenzyflame Thrust", stats:['dex','fai'], scale: {d:'B', f:'C'}, buffable: false, loc: "Liurnia (Invader)" },
        { id: 'wing', name: "Wing of Astel", type: 'Somber', bleed: false, dmg: 'Slash/Magic', skill: "Nebula", stats:['int','dex'], scale: {i:'B'}, buffable: false, loc: "Ainsel River" },
        { id: 'eleonora', name: "Eleonora's Poleblade", type: 'Somber', bleed: true, dmg: 'Standard/Fire', skill: "Bloodblade Dance", stats:['dex','arc'], scale: {d:'C', a:'D'}, buffable: false, loc: "Altus (Second Church)" },
        { id: 'radahn_s', name: "Starscourge Greatsword", type: 'Somber', bleed: false, dmg: 'Standard/Magic', skill: "Starcaller Cry", stats:['str'], scale: {s:'B'}, buffable: false, loc: "Caelid (Radahn Rem.)" },
        { id: 'magma', name: "Magma Wyrm's Scalesword", type: 'Somber', bleed: false, dmg: 'Slash/Fire', skill: "Magma Guillotine", stats:['str','fai'], scale: {s:'B', f:'B'}, buffable: false, loc: "Ruin-Strewn Precipice" },
        { id: 'magma_blade', name: "Magma Blade", type: 'Somber', bleed: false, dmg: 'Slash/Fire', skill: "Magma Shower", stats:['str','fai'], scale: {s:'C', f:'C'}, buffable: false, loc: "Volcano Manor (Man-Serpent Farm)" },
        { id: 'golden_order', name: "Golden Order Greatsword", type: 'Somber', bleed: false, dmg: 'Standard/Holy', skill: "Establish Order", stats:['fai','dex'], scale: {f:'B'}, buffable: false, loc: "Cave of the Forlorn" },
        { id: 'reduvia', name: "Reduvia", type: 'Somber', bleed: true, dmg: 'Slash', skill: "Reduvia Blood Blade", stats:['arc','dex'], scale: {a:'C'}, buffable: false, loc: "Limgrave (Invader Nerijus)" },
        { id: 'scythe', name: "Winged Scythe", type: 'Somber', bleed: true, dmg: 'Slash/Holy', skill: "Angel's Wings", stats:['fai','dex'], scale: {f:'C'}, buffable: false, loc: "Weeping Peninsula (Tombsward Ruins)" },
        { id: 'trina', name: "Sword of St. Trina", type: 'Somber', bleed: false, dmg: 'Slash/Magic', skill: "Mists of Slumber", stats:['dex','int'], scale: {d:'D'}, buffable: false, loc: "Caelid (Forsaken Ruins)" },
        { id: 'regalia', name: "Regalia of Eochaid", type: 'Somber', bleed: false, dmg: 'Standard/Magic', skill: "Eochaid's Dancing Blade", stats:['dex','arc'], scale: {d:'C', a:'D'}, buffable: false, loc: "Limgrave (Cliffside Reward)" },
        { id: 'giza', name: "Ghiza's Wheel", type: 'Somber', bleed: true, dmg: 'Standard', skill: "Spinning Wheel", stats:['str','dex'], scale: {s:'C', d:'C'}, buffable: false, loc: "Volcano Manor (Invader)" },
        { id: 'commander', name: "Commander's Standard", type: 'Somber', bleed: false, dmg: 'Standard', skill: "Rallying Standard", stats:['str'], scale: {s:'B'}, buffable: false, loc: "Caelid (Commander O'Neil)" },
        { id: 'halo', name: "Halo Scythe", type: 'Somber', bleed: true, dmg: 'Slash/Holy', skill: "Miquella's Ring of Light", stats:['dex','fai'], scale: {d:'C', f:'D'}, buffable: false, loc: "Caelid (Cleanrot Knight Farm)" },
        { id: 'siluria', name: "Siluria's Tree", type: 'Somber', bleed: false, dmg: 'Pierce/Holy', skill: "Siluria's Woe", stats:['str','fai'], scale: {s:'B', f:'C'}, buffable: false, loc: "Deeproot Depths (Crucible Knight)" },
        { id: 'treespear', name: "Treespear", type: 'Somber', bleed: false, dmg: 'Pierce/Holy', skill: "Sacred Order", stats:['dex','fai'], scale: {d:'C', f:'D'}, buffable: true, loc: "Liurnia Highway" },
        { id: 'vyke_spear', name: "Vyke's War Spear", type: 'Somber', bleed: false, dmg: 'Pierce/Fire', skill: "Frenzyflame Thrust", stats:['dex','fai'], scale: {d:'B', f:'C'}, buffable: false, loc: "Liurnia (Invader)" },
        { id: 'coded', name: "Coded Sword", type: 'Somber', bleed: false, dmg: 'Holy', skill: "Unblockable Blade", stats:['fai'], scale: {f:'A'}, buffable: false, loc: "Leyndell (Fortified Manor)" },
        { id: 'cipher', name: "Cipher Pata", type: 'Somber', bleed: false, dmg: 'Holy', skill: "Unblockable Blade", stats:['fai'], scale: {f:'B'}, buffable: false, loc: "Roundtable Hold (Balcony)" },
        { id: 'scepter', name: "Carian Regal Scepter", type: 'Somber', bleed: false, dmg: 'Magic', skill: "Spinning Weapon", stats:['int'], scale: {i:'S'}, buffable: false, loc: "Rennala Remembrance" },
        { id: 'lusat', name: "Lusat's Glintstone Staff", type: 'Somber', bleed: false, dmg: 'Strike', skill: "No Skill", stats:['int'], scale: {i:'S'}, buffable: false, loc: "Sellia Town of Sorcery" },
        { id: 'erdtree_seal', name: "Erdtree Seal", type: 'Somber', bleed: false, dmg: 'Strike', skill: "No Skill", stats:['fai'], scale: {f:'S'}, buffable: false, loc: "Volcano Manor" },
        { id: 'dragon_seal', name: "Dragon Communion Seal", type: 'Somber', bleed: false, dmg: 'Strike', skill: "No Skill", stats:['arc','fai'], scale: {a:'S', f:'B'}, buffable: false, loc: "Fringefolk Hero's Grave" },

        // --- STANDARD WEAPONS ---
        { id: 'guts', name: "Greatsword (Guts)", type: 'Std', bleed: false, dmg: 'Standard', stats:['str'], scale: {s:'A'}, loc: "Caelid (Dragonbarrow Caravan)" },
        { id: 'giant', name: "Giant-Crusher", type: 'Std', bleed: false, dmg: 'Strike', stats:['str'], scale: {s:'S'}, loc: "Altus (Outer Wall)" },
        { id: 'mace', name: "Great Mace", type: 'Std', bleed: false, dmg: 'Strike', stats:['str'], scale: {s:'A'}, loc: "Liurnia (Dectus Lift)" },
        { id: 'naga', name: "Nagakiba", type: 'Std', bleed: true, dmg: 'Slash/Pierce', stats:['dex'], scale: {d:'A'}, loc: "Yura Questline" },
        { id: 'uchi', name: "Uchigatana", type: 'Std', bleed: true, dmg: 'Slash/Pierce', stats:['dex'], scale: {d:'B'}, loc: "Limgrave Catacombs" },
        { id: 'clay', name: "Claymore", type: 'Std', bleed: false, dmg: 'Standard/Pierce', stats:['str','dex'], scale: {s:'C', d:'C'}, loc: "Castle Morne" },
        { id: 'zwei', name: "Zweihander", type: 'Std', bleed: false, dmg: 'Standard/Pierce', stats:['dex','str'], scale: {d:'B', s:'C'}, loc: "Weeping Peninsula Merchant" },
        { id: 'star', name: "Star Fist", type: 'Std', bleed: true, dmg: 'Strike', stats:['str'], scale: {s:'A'}, loc: "Leyndell Colosseum" },
        { id: 'night', name: "Nightrider Glaive", type: 'Std', bleed: false, dmg: 'Slash', stats:['str'], scale: {s:'S'}, loc: "Liurnia Night's Cavalry" },
        { id: 'cross', name: "Cross-Naginata", type: 'Std', bleed: true, dmg: 'Pierce', stats:['dex'], scale: {d:'B'}, loc: "Gael Tunnel" },
        { id: 'scav', name: "Scavenger's Curved Sword", type: 'Std', bleed: true, dmg: 'Slash', stats:['dex'], scale: {d:'C'}, loc: "Mt Gelmir" },
        { id: 'peel', name: "Godskin Peeler", type: 'Std', bleed: false, dmg: 'Standard', stats:['dex'], scale: {d:'A'}, loc: "Altus Windmill Village" },
        { id: 'ant', name: "Antspur Rapier", type: 'Std', bleed: false, dmg: 'Pierce', stats:['dex'], scale: {d:'C'}, loc: "Altus (Maleigh Marais)" },
        { id: 'mis', name: "Misericorde", type: 'Std', bleed: false, dmg: 'Pierce', stats:['dex'], scale: {d:'B'}, loc: "Stormveil Castle" },
        { id: 'exe', name: "Executioner's Greataxe", type: 'Std', bleed: false, dmg: 'Standard', stats:['str'], scale: {s:'A'}, loc: "Liurnia Skeleton Drop" },
        { id: 'grave', name: "Grave Scythe", type: 'Std', bleed: true, dmg: 'Slash', stats:['str','dex'], scale: {s:'C', d:'C'}, loc: "Skeleton Mage Drop" },
        { id: 'lance', name: "Lance", type: 'Std', bleed: false, dmg: 'Pierce', stats:['str'], scale: {s:'B'}, loc: "Limgrave Catacombs Top" },
        { id: 'pike', name: "Pike", type: 'Std', bleed: false, dmg: 'Pierce', stats:['str'], scale: {s:'C'}, loc: "Stormveil Castle" },
        { id: 'broad', name: "Broadsword", type: 'Std', bleed: false, dmg: 'Standard', stats:['str'], scale: {s:'C'}, loc: "Limgrave Merchant" },
        { id: 'long', name: "Longsword", type: 'Std', bleed: false, dmg: 'Standard/Pierce', stats:['str','dex'], scale: {s:'C', d:'D'}, loc: "Roundtable Hold" },
        { id: 'noble', name: "Noble's Slender Sword", type: 'Std', bleed: false, dmg: 'Standard/Pierce', stats:['dex'], scale: {d:'A'}, loc: "Noble Drop (Rare)" },
        { id: 'bandit', name: "Bandit's Curved Sword", type: 'Std', bleed: false, dmg: 'Slash', stats:['str','dex'], scale: {d:'C'}, loc: "Skeleton Drop" },
        { id: 'beastman', name: "Beastman's Curved Sword", type: 'Std', bleed: false, dmg: 'Slash', stats:['str'], scale: {s:'B'}, loc: "Azula Beastman Drop" },
        { id: 'omen', name: "Omen Cleaver", type: 'Std', bleed: false, dmg: 'Slash', stats:['str'], scale: {s:'B'}, loc: "Omen Drop" },
        { id: 'dismounter', name: "Dismounter", type: 'Std', bleed: false, dmg: 'Slash', stats:['dex'], scale: {d:'C'}, loc: "Kaiden Sellsword Drop" },
        { id: 'banish', name: "Banished Knight's Greatsword", type: 'Std', bleed: false, dmg: 'Standard/Pierce', stats:['str','dex'], scale: {s:'C', d:'C'}, loc: "Banished Knight Drop" },
        { id: 'flamberge', name: "Flamberge", type: 'Std', bleed: true, dmg: 'Standard/Pierce', stats:['dex'], scale: {d:'C'}, loc: "Redmane Castle" },
        { id: 'iron', name: "Iron Greatsword", type: 'Std', bleed: false, dmg: 'Standard', stats:['str'], scale: {s:'B'}, loc: "Misbegotten Drop" },
        { id: 'brick', name: "Brick Hammer", type: 'Std', bleed: false, dmg: 'Strike', stats:['str'], scale: {s:'A'}, loc: "Stormveil Castle" },
        { id: 'pick', name: "Pickaxe", type: 'Std', bleed: false, dmg: 'Pierce', stats:['str'], scale: {s:'B'}, loc: "Miner Drop" },
        { id: 'great_stars', name: "Great Stars", type: 'Std', bleed: true, dmg: 'Strike', stats:['str'], scale: {s:'A'}, loc: "Altus Carriage" },
        { id: 'butcher', name: "Butchering Knife", type: 'Std', bleed: false, dmg: 'Slash', stats:['dex'], scale: {d:'A'}, loc: "Anastasia Invader" },
        { id: 'guardian', name: "Guardian's Swordspear", type: 'Std', bleed: false, dmg: 'Slash', stats:['dex'], scale: {d:'A'}, loc: "Erdtree Guardian Drop" },
        { id: 'pest', name: "Pest's Glaive", type: 'Std', bleed: false, dmg: 'Slash', stats:['str','dex'], scale: {s:'C', d:'C'}, loc: "Pest Drop" },
        { id: 'vulgar', name: "Vulgar Militia Saw", type: 'Std', bleed: true, dmg: 'Slash', stats:['dex'], scale: {d:'B'}, loc: "Militia Drop" },
        { id: 'ripple', name: "Ripple Crescent Halberd", type: 'Std', bleed: false, dmg: 'Standard', stats:['arc'], scale: {a:'S'}, loc: "Albinauric Drop" },
        { id: 'hoslow', name: "Hoslow's Petal Whip", type: 'Std', bleed: true, dmg: 'Strike', stats:['dex'], scale: {d:'C'}, loc: "Volcano Manor Quest" },
        { id: 'urumi', name: "Urumi", type: 'Std', bleed: false, dmg: 'Slash', stats:['dex'], scale: {d:'B'}, loc: "Caria Manor" },
        { id: 'spiked', name: "Spiked Caestus", type: 'Std', bleed: true, dmg: 'Strike', stats:['str'], scale: {s:'B'}, loc: "Dragonbarrow Merchant" },
        { id: 'hookclaws', name: "Hookclaws", type: 'Std', bleed: true, dmg: 'Slash', stats:['dex'], scale: {d:'B'}, loc: "Stormveil Castle" },
        { id: 'raptor_talon', name: "Raptor Talons", type: 'Std', bleed: true, dmg: 'Slash', stats:['dex'], scale: {d:'B'}, loc: "Sage's Cave" },

        // --- DLC WEAPONS ---
        { id: 'milady', name: "Milady (DLC)", type: 'Std', bleed: false, dmg: 'Standard/Pierce', stats:['dex'], scale: {d:'B', s:'C'}, loc: "Castle Ensis" },
        { id: 'back', name: "Backhand Blade (DLC)", type: 'Std', bleed: false, dmg: 'Slash', stats:['dex'], scale: {d:'A'}, loc: "Gravesite Plain" },
        { id: 'fiend', name: "Bloodfiend's Arm (DLC)", type: 'Std', bleed: true, dmg: 'Strike', stats:['str','arc'], scale: {a:'S'}, loc: "Prospect Town" },
        { id: 'messmer', name: "Spear of the Impaler", type: 'Somber', bleed: false, dmg: 'Pierce/Fire', skill: "Messmer's Assault", stats:['dex','fai'], scale: {d:'B', f:'C'}, buffable: false, loc: "Messmer Remembrance" },
        { id: 'bayle_kat', name: "Dragon-Hunter's Katana", type: 'Somber', bleed: true, dmg: 'Slash/Pierce', skill: "Dragonwound Slash", stats:['str','dex'], scale: {s:'B', d:'B'}, buffable: false, loc: "Dragon's Pit Boss" },
        { id: 'rellana', name: "Rellana's Twin Blades", type: 'Somber', bleed: false, dmg: 'Magic/Fire', skill: "Moon-and-Fire", stats:['int','fai'], scale: {i:'C', f:'C'}, buffable: false, loc: "Rellana Remembrance" },
        { id: 'solitude', name: "Greatsword of Solitude", type: 'Somber', bleed: false, dmg: 'Standard', skill: "Solitary Moon Slash", stats:['str'], scale: {s:'A'}, buffable: false, loc: "Western Nameless Mausoleum" },
        { id: 'steel', name: "Black Steel Greathammer", type: 'Std', bleed: false, dmg: 'Strike', stats:['str','fai'], scale: {s:'A'}, loc: "Church of Consolation" },
        { id: 'perfume', name: "Lightning Perfume Bottle", type: 'Std', bleed: false, dmg: 'Lightning', stats:['dex','fai'], scale: {d:'C', f:'C'}, loc: "Cerulean Coast" },
        { id: 'anvil', name: "Anvil Hammer", type: 'Somber', bleed: false, dmg: 'Strike/Fire', skill: "Smithing Art Spears", stats:['str','fai'], scale: {s:'B', f:'C'}, buffable: false, loc: "Ruined Forge Lava Intake" },
        { id: 'pata', name: "Pata (DLC)", type: 'Std', bleed: false, dmg: 'Pierce', stats:['dex'], scale: {d:'B'}, loc: "Church of Benediction" },
        { id: 'dryleaf', name: "Dryleaf Arts (DLC)", type: 'Std', bleed: false, dmg: 'Strike', stats:['str','dex'], scale: {s:'C', d:'C'}, loc: "Moorth Ruins" },
        { id: 'dane', name: "Dane's Footwork (DLC)", type: 'Std', bleed: false, dmg: 'Strike', stats:['str','dex'], scale: {s:'C', d:'C'}, loc: "Enir-Ilim (Boss)" },
        { id: 'beast_claw', name: "Beast Claw (DLC)", type: 'Std', bleed: true, dmg: 'Slash', stats:['str','dex'], scale: {s:'C', d:'C'}, loc: "Gravesite Plain Wood" },
        { id: 'falx', name: "Falx (DLC)", type: 'Somber', bleed: true, dmg: 'Slash', skill: "Revenger's Blade", stats:['dex'], scale: {d:'B'}, buffable: false, loc: "Hornsent Questline" },
        { id: 'great_kat', name: "Great Katana (DLC)", type: 'Std', bleed: true, dmg: 'Slash/Pierce', stats:['dex','str'], scale: {d:'C', s:'D'}, loc: "Cerulean Coast (Dragon)" },
        { id: 'rakshasa', name: "Rakshasa's Great Katana", type: 'Somber', bleed: true, dmg: 'Slash/Pierce', skill: "Weed Cutter", stats:['dex','str'], scale: {d:'B'}, buffable: false, loc: "Eastern Nameless Mausoleum" },
        { id: 'star_line', name: "Star-Lined Sword (DLC)", type: 'Somber', bleed: true, dmg: 'Slash/Magic', skill: "Onze's Line of Stars", stats:['dex','int'], scale: {d:'B', i:'D'}, buffable: false, loc: "Demi-Human Queen Marigga" },
        { id: 'putre', name: "Putrescence Cleaver (DLC)", type: 'Somber', bleed: false, dmg: 'Standard/Magic', skill: "Spinning Guillotine", stats:['str','arc'], scale: {s:'C', a:'C'}, buffable: false, loc: "Putrescent Knight Remembrance" },
        { id: 'shadow', name: "Shadow Sunflower Blossom (DLC)", type: 'Somber', bleed: false, dmg: 'Strike/Holy', skill: "Shadow Sunflower Headbutt", stats:['str','fai'], scale: {s:'B', f:'C'}, buffable: false, loc: "Scadutree Avatar Remembrance" },
        { id: 'gaz', name: "Gazing Finger (DLC)", type: 'Somber', bleed: false, dmg: 'Strike/Magic', skill: "Kowtower's Resentment", stats:['str','int'], scale: {s:'C', i:'C'}, buffable: false, loc: "Metyr Remembrance" },
        { id: 'euporia', name: "Euporia (DLC)", type: 'Somber', bleed: false, dmg: 'Standard/Holy', skill: "Euporia Vortex", stats:['fai','dex'], scale: {f:'B', d:'C'}, buffable: false, loc: "Enir-Ilim (Secret Area)" },
        { id: 'light_great', name: "Leda's Sword (DLC)", type: 'Somber', bleed: false, dmg: 'Standard/Holy', skill: "Needle Piercer", stats:['dex','fai'], scale: {d:'B', f:'C'}, buffable: false, loc: "Leda Questline" },
        { id: 'queelign', name: "Queelign's Greatsword (DLC)", type: 'Std', bleed: false, dmg: 'Standard/Pierce', stats:['str','dex','fai'], scale: {d:'B', f:'C'}, loc: "Belurat Gaol" }
    ],
    shields: [
        { id: 'finger', name: "Fingerprint Stone Shield", type: 'Great', desc: "Highest guard boost.", loc: "Cathedral of Forsaken" },
        { id: 'visage', name: "Visage Shield", type: 'Great', desc: "Flamethrower skill.", loc: "Caelem Ruins" },
        { id: 'one_eye', name: "One-Eyed Shield", type: 'Great', desc: "Cannon skill.", loc: "Guardians' Garrison" },
        { id: 'erdtree', name: "Erdtree Greatshield", type: 'Great', desc: "Reflects magic.", loc: "Altus (Tree Sentinel Duo)" },
        { id: 'jelly', name: "Jellyfish Shield", type: 'Great', desc: "Boosts damage by 20%.", loc: "Liurnia West" },
        { id: 'ant', name: "Ant's Skull Plate", type: 'Great', desc: "Hardness bounces attacks.", loc: "Nokstella" },
        { id: 'icon', name: "Icon Shield", type: 'Great', desc: "Passive HP regen.", loc: "Altus (Woodfolk Ruins)" },
        { id: 'golden', name: "Golden Beast Crest", type: 'Great', desc: "Lightest Greatshield.", loc: "Grafted Scion (Start)" },
        { id: 'eclipse', name: "Eclipse Crest Greatshield", type: 'Great', desc: "Boosts Immunity.", loc: "Liurnia" },
        { id: 'brass', name: "Brass Shield", type: 'Med', desc: "Best medium guard boost.", loc: "Limgrave (Soldier Drop)" },
        { id: 'banish', name: "Banished Knight Shield", type: 'Med', desc: "High stability.", loc: "Stormveil (Knight Drop)" },
        { id: 'carian', name: "Carian Knight's Shield", type: 'Med', desc: "High magic negation.", loc: "Raya Lucaria" },
        { id: 'mirror', name: "Silver Mirrorshield", type: 'Med', desc: "Highest magic negation.", loc: "Apostate Derelict" },
        { id: 'turtle', name: "Great Turtle Shell", type: 'Med', desc: "Stamina recovery.", loc: "Weeping Peninsula" },
        { id: 'kite', name: "Kite Shield", type: 'Med', desc: "Standard balanced.", loc: "Liurnia Merchant" },
        { id: 'heater', name: "Heater Shield", type: 'Med', desc: "Light 100% phys block.", loc: "Roundtable Hold" },
        { id: 'buckler', name: "Buckler", type: 'Small', desc: "Best parry frames.", loc: "Stormveil (Gostoc)" },
        { id: 'coil', name: "Coil Shield", type: 'Small', desc: "Deadly poison bite.", loc: "Volcano Cave" },
        { id: 'rickety', name: "Rickety Shield", type: 'Small', desc: "Lightest shield.", loc: "Skeleton Drop" },
        { id: 'spiral', name: "Spiralhorn Shield", type: 'Small', desc: "Boosts status resist.", loc: "Uld Palace Ruins" },
        { id: 'smold', name: "Smoldering Shield", type: 'Small', desc: "Shield Bash fire dmg.", loc: "Volcano Manor" },
        { id: 'verdigris', name: "Verdigris Shield (DLC)", type: 'Great', desc: "Highest guard DLC.", loc: "Moore Questline" },
        { id: 'messmer_s', name: "Messmer Soldier Shield", type: 'Med', desc: "Good guard for weight.", loc: "DLC Soldier Drop" },
        { id: 'black_steel', name: "Black Steel Greatshield", type: 'Great', desc: "Holy negation tank.", loc: "DLC Black Knight" },
        { id: 'dueling', name: "Dueling Shield (DLC)", type: 'Small', desc: "Attack while blocking.", loc: "Shadow Keep" },
        { id: 'thrusting', name: "Carian Thrusting Shield (DLC)", type: 'Med', desc: "Attack while blocking.", loc: "Shadow Keep" }
    ],
    bosses: [
        // MAIN
        { id: 'margit', name: "Margit/Morgott", weak: ['Slash', 'Bleed'], resist: ['Holy'], tip: 'Use Margit\'s Shackle.' },
        { id: 'godrick', name: "Godrick the Grafted", weak: ['Bleed', 'Physical'], resist: ['Holy'], tip: 'Jump over his ground slams.' },
        { id: 'rennala', name: "Rennala", weak: ['Physical', 'Bleed'], resist: ['Magic'], tip: 'Stagger her constantly. She has 0 poise.' },
        { id: 'radagon', name: 'Radagon', weak: ['Fire', 'Strike'], resist: ['Holy', 'Bleed'], tip: 'Immune to bleed. Strike damage works best.' },
        { id: 'elden', name: 'Elden Beast', weak: ['Physical'], resist: ['Holy', 'Status'], tip: 'Target the chest scar. Use Pest Threads or Black Flame.' },
        { id: 'mohg', name: 'Mohg', weak: ['Bleed'], resist: ['Fire'], tip: 'Purifying Crystal Tear is mandatory.' },
        { id: 'malenia', name: 'Malenia', weak: ['Fire', 'Bleed', 'Frost', 'Stagger'], resist: ['Holy', 'Rot'], tip: 'Weak to stagger. Use Frost Pots for Waterfowl.' },
        { id: 'maliketh', name: 'Maliketh', weak: ['Physical'], resist: ['Holy'], tip: 'Low HP. Use Blasphemous Claw.' },
        { id: 'godfrey', name: "Godfrey/Hoarah Loux", weak: ['Slash', 'Lightning'], resist: ['Holy'], tip: 'Jump over his earthshatter stomps.' },
        { id: 'placid', name: 'Placidusax', weak: ['Pierce'], resist: ['Status'], tip: 'Ancient Dragon. Use Pierce damage to tail.' },
        { id: 'fortissax', name: "Lichdragon Fortissax", weak: ['Pierce'], resist: ['Lightning', 'Holy'], tip: 'Hit head/legs. Avoid death blight.' },
        { id: 'lansseax', name: "Lansseax", weak: ['Pierce'], resist: ['Lightning'], tip: 'Aim for the head.' },
        { id: 'rykard', name: 'Rykard', weak: ['Serpent'], resist: ['Fire'], tip: 'Must use Serpent-Hunter spear.' },
        { id: 'firegiant', name: 'Fire Giant', weak: ['Slash', 'Bleed'], resist: ['Fire'], tip: 'Attack the unarmored ankle, then hands.' },
        { id: 'godskin', name: 'Godskin Duo', weak: ['Sleep', 'Bleed', 'Slash'], resist: ['Holy', 'Fire'], tip: 'Throw Sleep Pots to isolate 1v1.' },
        { id: 'astel', name: "Astel, Naturalborn", weak: ['Physical'], resist: ['Magic', 'Elemental'], tip: 'Hit the head. Gravity magic.' },
        { id: 'ancestor', name: "Regal Ancestor Spirit", weak: ['Fire', 'Holy'], resist: ['Magic'], tip: 'Passive fight. Use Fire.' },
        { id: 'garg', name: "Valiant Gargoyles", weak: ['Strike', 'Magic'], resist: ['Slash', 'Fire'], tip: 'Immune to status. Use Magic/Strike.' },
        { id: 'commander', name: "Commander Niall", weak: ['Pierce'], resist: ['Frost'], tip: 'Use Bewitching Branch on his summons.' },
        { id: 'loretta', name: "Loretta (Haligtree)", weak: ['Lightning'], resist: ['Magic'], tip: 'Roll INTO the magic arrows.' },
        
        // SIDE / FIELD
        { id: 'tree', name: 'Draconic Tree Sentinel', weak: ['Strike', 'Rot'], resist: ['Lightning'], tip: 'Use Rotten Stray or Strike weapons.' },
        { id: 'night', name: "Night's Cavalry", weak: ['Lightning', 'Strike'], resist: ['Slash'], tip: 'Knock them off horse for critical.' },
        { id: 'bird', name: "Death Rite Bird", weak: ['Holy', 'Strike'], resist: ['Magic'], tip: 'Extremely weak to Holy Pots. Melt with Holy.' },
        { id: 'bell', name: "Bell Bearing Hunter", weak: ['Pierce', 'Lightning'], resist: ['Slash'], tip: 'Parry him. Do not heal far away.' },
        { id: 'watch', name: "Erdtree Watchdog", weak: ['Strike'], resist: ['Magic', 'Slash'], tip: 'Use Crystal Darts to glitch them.' },
        { id: 'crucible', name: "Crucible Knight", weak: ['Fire', 'Lightning'], resist: ['Slash', 'Holy'], tip: 'Parry is the best strategy.' },
        { id: 'avatar', name: "Erdtree Avatar", weak: ['Fire'], resist: ['Holy'], tip: 'Weak to fire. Easy to circle strafe.' },
        { id: 'runebear', name: "Runebear", weak: ['Sleep', 'Fire'], resist: ['Slash'], tip: 'Roll TOWARDS the bear. Sleep pots work.' },
        
        // DLC
        { id: 'lion', name: 'Divine Beast Dancing Lion', weak: ['Fire', 'Pierce'], resist: ['Holy'], tip: 'Weak to Pierce. Don\'t lock on under him.' },
        { id: 'rellana', name: 'Rellana (DLC)', weak: ['Lightning', 'Pierce'], resist: ['Magic', 'Fire'], tip: 'Parry her. Jump moon moons.' },
        { id: 'hippo', name: 'Golden Hippo (DLC)', weak: ['Lightning', 'Slash'], resist: ['Holy'], tip: 'Use Lightning. Hit head.' },
        { id: 'messmer', name: 'Messmer (DLC)', weak: ['Bleed', 'Frost', 'Slash'], resist: ['Fire'], tip: 'Resists Fire. Punish snake attacks.' },
        { id: 'romina', name: 'Romina (DLC)', weak: ['Bleed', 'Frost'], resist: ['Rot'], tip: 'Fast attacks. Use Bleed.' },
        { id: 'gaius', name: 'Gaius (DLC)', weak: ['Holy', 'Lightning'], resist: ['Physical'], tip: 'Dodge INTO charge. Use Holy.' },
        { id: 'scadu', name: 'Scadutree Avatar (DLC)', weak: ['Fire'], resist: ['Holy'], tip: 'Hit the head (flower). Use Fire.' },
        { id: 'metyr', name: "Metyr, Mother of Fingers", weak: ['Bleed', 'Frost'], resist: ['Magic'], tip: 'Hit the fleshy parts.' },
        { id: 'midra', name: 'Midra (DLC)', weak: ['Bleed', 'Slash'], resist: ['Fire'], tip: 'Very low poise. Stagger him.' },
        { id: 'bayle', name: 'Bayle (DLC)', weak: ['Dragon'], resist: ['Lightning', 'Fire'], tip: 'Use Dragon-Hunter Katana skill.' },
        { id: 'putre', name: "Putrescent Knight", weak: ['Holy', 'Fire'], resist: ['Poison'], tip: 'Jump the blue flames.' },
        { id: 'radahn_dlc', name: 'Consort Radahn', weak: ['Pierce', 'Rot', 'Bleed'], resist: ['Holy', 'Slash'], tip: 'Use Greatshield + Poke weapon.' }
    ],
    affinities: [
        { id: 'std', name: 'Standard', canBuff: true, desc: "Default scaling." }, { id: 'heavy', name: 'Heavy', canBuff: true, desc: "Str scaling." }, 
        { id: 'keen', name: 'Keen', canBuff: true, desc: "Dex scaling." }, { id: 'qual', name: 'Quality', canBuff: true, desc: "Str/Dex scaling." }, 
        { id: 'magic', name: 'Magic', type:'Magic', canBuff: false, desc: "Int scaling." }, { id: 'fire', name: 'Fire', type:'Fire', canBuff: false, desc: "Str scaling." },
        { id: 'flame', name: 'Flame Art', type:'Fire', canBuff: false, desc: "Fai scaling." }, { id: 'light', name: 'Lightning', type:'Lightning', canBuff: false, desc: "Dex scaling." },
        { id: 'sacred', name: 'Sacred', type:'Holy', canBuff: false, desc: "Fai scaling." }, { id: 'blood', name: 'Blood', type:'Phys', effect:'Bleed', canBuff: false, desc: "Arc scaling + Bleed." },
        { id: 'occult', name: 'Occult', type:'Phys', canBuff: false, desc: "Arc scaling." }, { id: 'cold', name: 'Cold', type:'Magic', effect:'Frost', canBuff: false, desc: "Int scaling + Frost." },
        { id: 'poison', name: 'Poison', type:'Phys', effect:'Poison', canBuff: false, desc: "Arc scaling + Poison." }
    ],
    ashes: [
        { id: 'lion', name: "Lion's Claw", type: 'Phys', desc: "Somersault slam. Huge hyper armor." }, 
        { id: 'unsheathe', name: "Unsheathe", type: 'Phys', desc: "Fast katana stance. High poise damage." },
        { id: 'sep', name: "Seppuku", type: 'Phys', desc: "Massive bleed buff at cost of HP." },
        { id: 'crag', name: "Cragblade", type: 'Phys', desc: "Buffs weapon Physical Dmg & Stance Dmg." },
        { id: 'flame', name: "Flaming Strike", type: 'Fire', desc: "Fire arc + heavy attack buffs weapon." },
        { id: 'sacred', name: "Sacred Blade", type: 'Holy', desc: "Fires holy projectile + buffs weapon." },
        { id: 'ice', name: "Ice Spear", type: 'Magic', desc: "Fires ice projectile. Huge Frost buildup." },
        { id: 'impale', name: "Impaling Thrust", type: 'Phys', desc: "Quick thrust. Pierces shields." },
        { id: 'pierce', name: "Piercing Fang", type: 'Phys', desc: "Lunging thrust. Ignores shields entirely." },
        { id: 'royal', name: "Royal Knight's Resolve", type: 'Phys', desc: "+80% damage on next hit." },
        { id: 'endure', name: "Endure", type: 'Phys', desc: "Briefly boosts poise and defense." },
        { id: 'giant', name: "Giant Hunt", type: 'Phys', desc: "Launches foes into air. Great roll catch." },
        { id: 'phantom', name: "Phantom Slash", type: 'Phys', desc: "Summons phantom for range + gap close." },
        { id: 'sword', name: "Sword Dance", type: 'Phys', desc: "Rapid gap closing combo." },
        { id: 'double', name: "Double Slash", type: 'Phys', desc: "Genichiro combo. Great with Bloodflame." },
        { id: 'glint', name: "Glintstone Pebble", type: 'Magic', desc: "Magic dart + thrust combo. True combo." },
        { id: 'storm', name: "Storm Blade", type: 'Phys', desc: "Ranged wind projectile. Spammable." },
        { id: 'caller', name: "Stormcaller", type: 'Phys', desc: "Traps enemies in wind storm." },
        { id: 'step', name: "Bloodhound's Step", type: 'Phys', desc: "Invisible dodge. High i-frames." },
        { id: 'quick', name: "Quickstep", type: 'Phys', desc: "Fast dodge. Good for backstabs." },
        { id: 'grand', name: "Carian Grandeur", type: 'Magic', desc: "Chargeable magic sword. Nuclear damage." },
        { id: 'prelate', name: "Prelate's Charge", type: 'Fire', desc: "Run forward with fire. Stunlocks." },
        { id: 'tornado', name: "Black Flame Tornado", type: 'Fire', desc: "Melts bosses with % HP damage." },
        { id: 'waves', name: "Waves of Darkness", type: 'Magic', desc: "3-hit gravity AoE. Hyper armor." },
        { id: 'hoar', name: "Hoarfrost Stomp", type: 'Magic', desc: "Cone frost AoE. Fast cast." },
        { id: 'light', name: "Lightning Slash", type: 'Lightning', desc: "Lightning strike + buffs weapon." },
        { id: 'bolt', name: "Thunderbolt", type: 'Lightning', desc: "Ranged lightning strike from above." },
        { id: 'pray', name: "Prayerful Strike", type: 'Holy', desc: "Slow slam that heals 30% HP." },
        { id: 'gold_vow', name: "Golden Vow (AoW)", type: 'Holy', desc: "Buffs Atk & Def." },
        { id: 'erupt', name: "Eruption", type: 'Fire', desc: "Lava slam. Leaves lava pool." },
        { id: 'grav', name: "Gravitas", type: 'Magic', desc: "Pulls enemies in. Good for flyers." },
        { id: 'wild', name: "Wild Strikes", type: 'Phys', desc: "Continuous swinging. High poise." },
        { id: 'roar', name: "Braggart's Roar", type: 'Phys', desc: "Buffs Atk, Def, Stamina recovery." },
        { id: 'stamp', name: "Stamp (Upward)", type: 'Phys', desc: "Tanks hit then launches enemy." },
        { id: 'parry', name: "Parry", type: 'Phys', desc: "Deflects attacks to allow crit." },
        { id: 'carian', name: "Carian Retaliation", type: 'Magic', desc: "Parries spells into glintblades." },
        { id: 'wall', name: "Storm Wall", type: 'Phys', desc: "Parries attacks and deflects arrows." },
        { id: 'bash', name: "Shield Bash", type: 'Phys', desc: "Attack while blocking." },
        { id: 'barr', name: "Barricade Shield", type: 'Phys', desc: "Temporarily boosts shield hardness." },
        { id: 'raptor', name: "Raptor of the Mists", type: 'Phys', desc: "Jump into air when hit." },
        { id: 'assassin', name: "Assassin's Gambit", type: 'Phys', desc: "Become nearly invisible." },
        { id: 'lure', name: "White Shadow's Lure", type: 'Phys', desc: "Distracts humanoids." },
        { id: 'life', name: "Lifesteal Fist", type: 'Magic', desc: "Grabs humanoids, steals HP/FP." },
        { id: 'ground', name: "Ground Slam", type: 'Phys', desc: "Butt slam. AoE shockwave." },
        { id: 'kick', name: "Kick", type: 'Phys', desc: "Instantly breaks guard." },
        { id: 'repeat', name: "Repeating Thrust", type: 'Phys', desc: "Rapid flurry of thrusts." },
        { id: 'charge', name: "Charge Forth", type: 'Phys', desc: "Long distance charge attack." },
        { id: 'poison', name: "Poisonous Mist", type: 'Phys', desc: "Releases poison cloud." },
        { id: 'chill', name: "Chilling Mist", type: 'Magic', desc: "Releases frost cloud + buffs weapon." },
        { id: 'wing', name: "Wing Stance (DLC)", type: 'Phys', desc: "Elegant combo stance." },
        { id: 'savage', name: "Savage Lion's Claw (DLC)", type: 'Phys', desc: "Lion's Claw with follow-up." },
        { id: 'blind', name: "Blind Spot (DLC)", type: 'Phys', desc: "Side dash stab. Ignores shields." },
        { id: 'swift', name: "Swift Slash (DLC)", type: 'Phys', desc: "Anime dash attack." },
        { id: 'roll', name: "Rolling Sparks (DLC)", type: 'Fire', desc: "Explosive perfume trail." },
        { id: 'palm', name: "Palm Blast (DLC)", type: 'Phys', desc: "Chargeable palm strike." }
    ],
    talismans: [
        { id: 'shard', name: "Shard of Alexander", tag: 'skill', desc: "Boosts Skill damage by 15%." }, 
        { id: 'blood', name: "Lord of Blood's Exultation", tag: 'bleed', desc: "Atk +20% when Bleed occurs." },
        { id: 'rot', name: "Kindred of Rot", tag: 'rot', desc: "Atk +20% when Poison/Rot occurs." }, 
        { id: 'claw', name: "Claw Talisman", tag: 'jump', desc: "Boosts Jump Attacks by 15%." },
        { id: 'curved', name: "Curved Sword Talisman", tag: 'guard', desc: "Boosts Guard Counters by 20%." }, 
        { id: 'axe', name: "Axe Talisman", tag: 'charge', desc: "Boosts Charged Attacks by 10%." },
        { id: 'spear', name: "Spear Talisman", tag: 'counter', desc: "Boosts Counter Dmg (Pierce) by 15%." },
        { id: 'hammer', name: "Hammer Talisman", tag: 'stam', desc: "Increases stamina dmg against shields." },
        { id: 'dagger', name: "Dagger Talisman", tag: 'crit', desc: "Boosts Critical Hits by 17%." },
        { id: 'fire', name: "Fire Scorpion Charm", tag: 'fire', desc: "Fire Dmg +12%, Defense -10%." }, 
        { id: 'magic', name: "Magic Scorpion Charm", tag: 'magic', desc: "Magic Dmg +12%, Defense -10%." },
        { id: 'holy', name: "Sacred Scorpion Charm", tag: 'holy', desc: "Holy Dmg +12%, Defense -10%." }, 
        { id: 'light', name: "Lightning Scorpion Charm", tag: 'light', desc: "Lightning Dmg +12%, Defense -10%." },
        { id: 'rotten', name: "Rotten Winged Sword", tag: 'multi', desc: "Greatly boosts Atk on consecutive hits." },
        { id: 'mill', name: "Millicent's Prosthesis", tag: 'multi', desc: "Boosts Atk on hits +5 DEX." },
        { id: 'godskin', name: "Godskin Swaddling Cloth", tag: 'heal', desc: "Heals HP on consecutive hits." },
        { id: 'ritual_s', name: "Ritual Sword Talisman", tag: 'fullhp', desc: "Atk +10% when HP is full." },
        { id: 'ritual_d', name: "Ritual Shield Talisman", tag: 'fullhp', desc: "Def +30% when HP is full." },
        { id: 'red', name: "Red-Feathered Branchsword", tag: 'lowhp', desc: "Atk +20% when HP is low." },
        { id: 'blue', name: "Blue-Feathered Branchsword", tag: 'lowhp', desc: "Def +50% when HP is low." },
        { id: 'dragon', name: "Dragoncrest Greatshield", tag: 'def', desc: "+20% Phys Defense." },
        { id: 'pearl', name: "Pearldrake Talisman +2", tag: 'def', desc: "Boosts Non-Phys Negation." },
        { id: 'turtle', name: "Green Turtle Talisman", tag: 'stam', desc: "Boosts Stamina Regen." },
        { id: 'amber_h', name: "Crimson Amber +2", tag: 'stat', desc: "Greatly boosts Max HP." },
        { id: 'amber_f', name: "Cerulean Amber +2", tag: 'stat', desc: "Greatly boosts Max FP." },
        { id: 'amber_s', name: "Viridian Amber +2", tag: 'stat', desc: "Greatly boosts Max Stamina." },
        { id: 'favor', name: "Erdtree's Favor +2", tag: 'stat', desc: "Boosts HP, Stamina, Equip Load." },
        { id: 'arsenal', name: "Great-Jar's Arsenal", tag: 'equip', desc: "Greatly boosts Equip Load." },
        { id: 'rad_sore', name: "Radagon's Soreseal", tag: 'stat', desc: "+5 Vig/End/Str/Dex, more dmg taken." },
        { id: 'mar_sore', name: "Marika's Soreseal", tag: 'stat', desc: "+5 Mind/Int/Fai/Arc, more dmg taken." },
        { id: 'bull', name: "Bull-Goat's Talisman", tag: 'poise', desc: "Boosts Poise by 33%." },
        { id: 'godfrey', name: "Godfrey Icon", tag: 'charge', desc: "Boosts Charged Spells/Skills." },
        { id: 'rad_icon', name: "Radagon Icon", tag: 'cast', desc: "Shortens spell casting time." },
        { id: 'flock', name: "Flock's Canvas Talisman", tag: 'incant', desc: "Greatly boosts Incantations." },
        { id: 'graven', name: "Graven-Mass Talisman", tag: 'sorc', desc: "Greatly boosts Sorceries." },
        { id: 'old', name: "Old Lord's Talisman", tag: 'buff', desc: "Extends spell effect duration." },
        { id: 'carian', name: "Carian Filigreed Crest", tag: 'fp', desc: "Lowers Skill FP cost." },
        { id: 'taker', name: "Taker's Cameo", tag: 'heal', desc: "Restores HP on kill." },
        { id: 'ancestor', name: "Ancestral Spirit's Horn", tag: 'fp', desc: "Restores FP on kill." },
        { id: 'gold', name: "Gold Scarab", tag: 'farm', desc: "Increases Rune acquisition." },
        { id: 'silver', name: "Silver Scarab", tag: 'farm', desc: "Increases Item Discovery." },
        { id: 'crepus', name: "Crepus's Vial", tag: 'stealth', desc: "Silent movement." },
        { id: 'shabriri', name: "Shabriri's Woe", tag: 'aggro', desc: "Attracts enemy aggression." },
        { id: 'cat', name: "Longtail Cat Talisman", tag: 'util', desc: "Prevents fall damage." },
        { id: 'star_h', name: "Starscourge Heirloom", tag: 'stat', desc: "Raises STR by 5." },
        { id: 'pros_h', name: "Prosthesis-Wearer Heirloom", tag: 'stat', desc: "Raises DEX by 5." },
        { id: 'gazer', name: "Stargazer Heirloom", tag: 'stat', desc: "Raises INT by 5." },
        { id: 'finger', name: "Two Fingers Heirloom", tag: 'stat', desc: "Raises FAI by 5." },
        { id: 'blue_dance', name: "Blue Dancer Charm", tag: 'naked', desc: "Higher dmg with low weight." },
        { id: 'crusade', name: "Crusade Insignia (DLC)", tag: 'heal', desc: "Boosts Atk after kill." },
        { id: 'braid', name: "Golden Braid (DLC)", tag: 'def', desc: "Max Holy Negation." },
        { id: 'two_head', name: "Two-Headed Turtle (DLC)", tag: 'stam', desc: "Max Stamina Regen." },
        { id: 'smith', name: "Smithing Talisman (DLC)", tag: 'throw', desc: "Boosts Throwing Weapons." },
        { id: 'blade', name: "Blade of Mercy (DLC)", tag: 'crit', desc: "Boosts Atk after Crit." },
        { id: 'dried', name: "Dried Bouquet (DLC)", tag: 'sum', desc: "Boosts Atk when summon dies." },
        { id: 'enrage', name: "Enraged Divine Beast (DLC)", tag: 'storm', desc: "Boosts Storm Skills." },
        { id: 'shat', name: "Shattered Stone (DLC)", tag: 'kick', desc: "Boosts Kicks/Stomps." },
        { id: 'aim', name: "Arrow's Soaring Sting (DLC)", tag: 'bow', desc: "Boosts Arrow Range/Dmg." },
        { id: 'talisman_dread', name: "Talisman of the Dread (DLC)", tag: 'magma', desc: "Boosts Magma/Volcano Skills." }
    ],
    buffs: [
        { id: 'vow', name: "Golden Vow (Spell)", desc: "+15% Dmg, +10% Def (Body Buff)." },
        { id: 'fgms', name: "Flame, Grant Me Strength", desc: "+20% Phys/Fire Dmg (Body Buff)." },
        { id: 'terra', name: "Terra Magica", desc: "+35% Magic Dmg zone." },
        { id: 'shab', name: "Howl of Shabriri", desc: "+25% Dmg given, +30% Dmg taken." },
        { id: 'bloodflame', name: "Bloodflame Blade", desc: "Adds Blood/Fire to weapon." },
        { id: 'blackflame', name: "Black Flame's Protection", desc: "+35% Phys Negation." },
        { id: 'electrify', name: "Electrify Armament", desc: "Adds Lightning Dmg." },
        { id: 'order', name: "Order's Blade", desc: "Adds Holy Dmg. Kills Undead." },
        { id: 'poison_w', name: "Poison Armament", desc: "Adds Poison Dmg." },
        { id: 'frozen', name: "Frozen Armament", desc: "Adds Frostbite." },
        { id: 'scholars', name: "Scholar's Armament", desc: "Adds Magic Dmg." },
        { id: 'vyke_drag', name: "Vyke's Dragonbolt", desc: "Adds Lightning Dmg + Equip Load." },
        { id: 'protect', name: "Protection of the Erdtree", desc: "Boosts Holy Negation." },
        { id: 'barrier', name: "Barrier of Gold", desc: "Boosts Magic Negation." },
        { id: 'lord', name: "Lord's Divine Fortification", desc: "Boosts Holy Negation (Massive)." },
        { id: 'flame_p', name: "Flame, Protect Me", desc: "Boosts Fire Negation." }
    ],
    greases: [
        { id: 'fire', name: "Fire Grease" }, { id: 'magic', name: "Magic Grease" },
        { id: 'light', name: "Lightning Grease" }, { id: 'holy', name: "Holy Grease" },
        { id: 'blood', name: "Blood Grease" }, { id: 'freeze', name: "Freezing Grease" },
        { id: 'rot', name: "Rot Grease" }, { id: 'sleep', name: "Soporific Grease" },
        { id: 'poison', name: "Poison Grease" }, { id: 'dragon', name: "Dragonwound Grease" },
        { id: 'shield', name: "Shield Grease" }
    ]
};
