const DB = {
    weapons: [
        // --- SOMBER (UNIQUE) ---
        { id: 'rob', name: "Rivers of Blood", type: 'Somber', bleed: true, dmg: 'Slash/Fire', skill: "Corpse Piler", stats:['dex','arc'], scale: {d:'B', a:'D'}, buffable: false, loc: "Mountaintops (Church of Repose)" },
        { id: 'moon', name: "Moonveil", type: 'Somber', bleed: true, dmg: 'Slash/Magic', skill: "Transient Moonlight", stats:['dex','int'], scale: {d:'B', i:'B'}, buffable: false, loc: "Caelid (Gael Tunnel)" },
        { id: 'blas', name: "Blasphemous Blade", type: 'Somber', bleed: false, dmg: 'Standard/Fire', skill: "Taker's Flames", stats:['str','fai'], scale: {s:'C', f:'B'}, buffable: false, loc: "Volcano Manor (Rykard Rem.)" },
        { id: 'fang', name: "Bloodhound's Fang", type: 'Somber', bleed: true, dmg: 'Slash', skill: "Bloodhound's Finesse", stats:['dex','str'], scale: {d:'B', s:'C'}, buffable: true, loc: "Limgrave (Forlorn Hound Evergaol)" },
        { id: 'ruins', name: "Ruins Greatsword", type: 'Somber', bleed: false, dmg: 'Standard/Magic', skill: "Wave of Destruction", stats:['str'], scale: {s:'S'}, buffable: false, loc: "Redmane Castle Plaza" },
        { id: 'mohg', name: "Mohgwyn's Spear", type: 'Somber', bleed: true, dmg: 'Pierce/Fire', skill: "Bloodboon Ritual", stats:['str','arc'], scale: {a:'C', s:'C'}, buffable: false, loc: "Mohgwyn Palace (Mohg Rem.)" },
        { id: 'dark', name: "Dark Moon Greatsword", type: 'Somber', bleed: false, dmg: 'Standard/Magic', skill: "Moonlight Greatsword", stats:['int','str'], scale: {i:'B'}, buffable: false, loc: "Liurnia (Ranni Quest)" },
        { id: 'bolt', name: "Bolt of Gransax", type: 'Somber', bleed: false, dmg: 'Pierce/Lightning', skill: "Ancient Lightning Spear", stats:['dex'], scale: {d:'B'}, buffable: false, loc: "Leyndell Capital" },
        { id: 'morgott', name: "Morgott's Cursed Sword", type: 'Somber', bleed: true, dmg: 'Slash/Fire', skill: "Cursed-Blood Slice", stats:['dex','arc'], scale: {d:'B', a:'D'}, buffable: false, loc: "Leyndell (Morgott Rem.)" },
        { id: 'godslayer', name: "Godslayer's Greatsword", type: 'Somber', bleed: false, dmg: 'Standard/Fire', skill: "Queen's Black Flame", stats:['dex','fai'], scale: {d:'B', f:'C'}, buffable: false, loc: "Caelid (Divine Tower)" },
        { id: 'black_knife', name: "Black Knife", type: 'Somber', bleed: false, dmg: 'Slash/Holy', skill: "Blade of Death", stats:['dex','fai'], scale: {f:'B'}, buffable: false, loc: "Altus (Sainted Hero's Grave)" },
        { id: 'vyke', name: "Vyke's War Spear", type: 'Somber', bleed: false, dmg: 'Pierce/Fire', skill: "Frenzyflame Thrust", stats:['dex','fai'], scale: {d:'B', f:'C'}, buffable: false, loc: "Liurnia (Invader)" },
        { id: 'wing', name: "Wing of Astel", type: 'Somber', bleed: false, dmg: 'Slash/Magic', skill: "Nebula", stats:['int','dex'], scale: {i:'B'}, buffable: false, loc: "Ainsel River" },
        { id: 'ordovis', name: "Ordovis's Greatsword", type: 'Somber', bleed: false, dmg: 'Standard/Holy', skill: "Ordovis's Vortex", stats:['str','fai'], scale: {s:'A', f:'C'}, buffable: false, loc: "Altus (Auriza Hero's Grave)" },
        { id: 'eleonora', name: "Eleonora's Poleblade", type: 'Somber', bleed: true, dmg: 'Standard/Fire', skill: "Bloodblade Dance", stats:['dex','arc'], scale: {d:'C', a:'D'}, buffable: false, loc: "Altus (Second Church)" },
        { id: 'maliketh_b', name: "Maliketh's Black Blade", type: 'Somber', bleed: false, dmg: 'Standard/Holy', skill: "Destined Death", stats:['str','fai'], scale: {s:'B', f:'B'}, buffable: false, loc: "Farum Azula (Maliketh Rem.)" },
        { id: 'radahn_s', name: "Starscourge Greatsword", type: 'Somber', bleed: false, dmg: 'Standard/Magic', skill: "Starcaller Cry", stats:['str'], scale: {s:'B'}, buffable: false, loc: "Caelid (Radahn Rem.)" },
        { id: 'magma', name: "Magma Wyrm's Scalesword", type: 'Somber', bleed: false, dmg: 'Slash/Fire', skill: "Magma Guillotine", stats:['str','fai'], scale: {s:'B', f:'B'}, buffable: false, loc: "Ruin-Strewn Precipice" },
        { id: 'golden_order', name: "Golden Order Greatsword", type: 'Somber', bleed: false, dmg: 'Standard/Holy', skill: "Establish Order", stats:['fai','dex'], scale: {f:'B'}, buffable: false, loc: "Cave of the Forlorn" },
        { id: 'reduvia', name: "Reduvia", type: 'Somber', bleed: true, dmg: 'Slash', skill: "Reduvia Blood Blade", stats:['arc','dex'], scale: {a:'C'}, buffable: false, loc: "Limgrave (Invader Nerijus)" },
        { id: 'scythe', name: "Winged Scythe", type: 'Somber', bleed: true, dmg: 'Slash/Holy', skill: "Angel's Wings", stats:['fai','dex'], scale: {f:'C'}, buffable: false, loc: "Weeping Peninsula (Tombsward Ruins)" },
        { id: 'trina', name: "Sword of St. Trina", type: 'Somber', bleed: false, dmg: 'Slash/Magic', skill: "Mists of Slumber", stats:['dex','int'], scale: {d:'D'}, buffable: false, loc: "Caelid (Forsaken Ruins)" },
        { id: 'regalia', name: "Regalia of Eochaid", type: 'Somber', bleed: false, dmg: 'Standard/Magic', skill: "Eochaid's Dancing Blade", stats:['dex','arc'], scale: {d:'C', a:'D'}, buffable: false, loc: "Limgrave (Cliffside Reward)" },
        { id: 'carian_regal', name: "Carian Regal Scepter", type: 'Somber', bleed: false, dmg: 'Standard/Magic', skill: "Spinning Weapon", stats:['int'], scale: {i:'S'}, buffable: false, loc: "Rennala's Remembrance" },
        { id: 'lusat', name: "Lusat's Glintstone Staff", type: 'Somber', bleed: false, dmg: 'Strike', skill: "No Skill", stats:['int'], scale: {i:'S'}, buffable: false, loc: "Sellia, Town of Sorcery" },
        { id: 'erdtree_seal', name: "Erdtree Seal", type: 'Somber', bleed: false, dmg: 'Strike', skill: "No Skill", stats:['fai'], scale: {f:'S'}, buffable: false, loc: "Volcano Manor (Prison Town)" },
        { id: 'dragon_comm', name: "Dragon Communion Seal", type: 'Somber', bleed: false, dmg: 'Strike', skill: "No Skill", stats:['arc','fai'], scale: {a:'S'}, buffable: false, loc: "Fringefolk Hero's Grave" },
        
        // --- STANDARD (CUSTOMIZABLE) ---
        { id: 'guts', name: "Greatsword (Guts)", type: 'Std', bleed: false, dmg: 'Standard', stats:['str'], scale: {s:'A'}, loc: "Caelid (Dragonbarrow Caravan)" },
        { id: 'mace', name: "Great Mace", type: 'Std', bleed: false, dmg: 'Strike', stats:['str'], scale: {s:'A'}, loc: "Liurnia (Grand Lift Dectus Chest)" },
        { id: 'giant', name: "Giant-Crusher", type: 'Std', bleed: false, dmg: 'Strike', stats:['str'], scale: {s:'S'}, loc: "Altus (Outer Wall Caravan)" },
        { id: 'star', name: "Star Fist", type: 'Std', bleed: true, dmg: 'Strike', stats:['str'], scale: {s:'A'}, loc: "Leyndell (Colosseum)" },
        { id: 'naga', name: "Nagakiba", type: 'Std', bleed: true, dmg: 'Slash/Pierce', stats:['dex'], scale: {d:'A'}, loc: "Limgrave/Altus (Yura Quest)" },
        { id: 'uchi', name: "Uchigatana", type: 'Std', bleed: true, dmg: 'Slash/Pierce', stats:['dex'], scale: {d:'B'}, loc: "Limgrave (Catacombs)" },
        { id: 'clay', name: "Claymore", type: 'Std', bleed: false, dmg: 'Standard/Pierce', stats:['str','dex'], scale: {s:'C', d:'C'}, loc: "Weeping Peninsula (Castle Morne)" },
        { id: 'zwei', name: "Zweihander", type: 'Std', bleed: false, dmg: 'Standard/Pierce', stats:['dex','str'], scale: {d:'B', s:'C'}, loc: "Weeping Peninsula (Merchant)" },
        { id: 'night', name: "Nightrider Glaive", type: 'Std', bleed: false, dmg: 'Slash', stats:['str'], scale: {s:'S'}, loc: "Liurnia (Night's Cavalry)" },
        { id: 'cross', name: "Cross-Naginata", type: 'Std', bleed: true, dmg: 'Pierce', stats:['dex'], scale: {d:'B'}, loc: "Caelid (Gael Tunnel)" },
        { id: 'ant', name: "Antspur Rapier", type: 'Std', bleed: false, dmg: 'Pierce', stats:['dex'], scale: {d:'C'}, loc: "Altus (Maleigh Marais NPC)" },
        { id: 'scav', name: "Scavenger's Curved Sword", type: 'Std', bleed: true, dmg: 'Slash', stats:['dex'], scale: {d:'C'}, loc: "Mt Gelmir" },
        { id: 'peel', name: "Godskin Peeler", type: 'Std', bleed: false, dmg: 'Standard', stats:['dex'], scale: {d:'A'}, loc: "Altus (Windmill Village)" },
        { id: 'hook', name: "Hookclaws", type: 'Std', bleed: true, dmg: 'Slash', stats:['dex'], scale: {d:'B'}, loc: "Stormveil Castle" },
        { id: 'mis', name: "Misericorde", type: 'Std', bleed: false, dmg: 'Pierce', stats:['dex'], scale: {d:'B'}, loc: "Stormveil Castle" },
        { id: 'exe', name: "Executioner's Greataxe", type: 'Std', bleed: false, dmg: 'Standard', stats:['str'], scale: {s:'A'}, loc: "Liurnia (Skeleton Drop)" },
        { id: 'grave', name: "Grave Scythe", type: 'Std', bleed: true, dmg: 'Slash', stats:['str','dex'], scale: {s:'C', d:'C'}, loc: "Liurnia (Skeleton Mage Drop)" },
        { id: 'lance', name: "Lance", type: 'Std', bleed: false, dmg: 'Pierce', stats:['str'], scale: {s:'B'}, loc: "Limgrave (Deathtouched Catacombs Top)" },
        { id: 'broad', name: "Broadsword", type: 'Std', bleed: false, dmg: 'Standard', stats:['str'], scale: {s:'C'}, loc: "Limgrave (Merchant)" },
        { id: 'bandit', name: "Bandit's Curved Sword", type: 'Std', bleed: false, dmg: 'Slash', stats:['str','dex'], scale: {d:'C'}, loc: "Weeping Peninsula (Skeleton Drop)" },
        { id: 'rogiers', name: "Rogier's Rapier", type: 'Std', bleed: false, dmg: 'Pierce', stats:['dex'], scale: {d:'B'}, loc: "Roundtable (Rogier)" },
        { id: 'pike', name: "Pike", type: 'Std', bleed: false, dmg: 'Pierce', stats:['str'], scale: {s:'C'}, loc: "Stormveil Castle" },
        { id: 'morning', name: "Morning Star", type: 'Std', bleed: true, dmg: 'Strike', stats:['str'], scale: {s:'C'}, loc: "Weeping Peninsula" },
        { id: 'banish', name: "Banished Knight's Greatsword", type: 'Std', bleed: false, dmg: 'Standard/Pierce', stats:['str','dex'], scale: {s:'C', d:'C'}, loc: "Dragon Communion (Farm)" },
        
        // --- DLC WEAPONS ---
        { id: 'milady', name: "Milady (DLC)", type: 'Std', bleed: false, dmg: 'Standard/Pierce', stats:['dex'], scale: {d:'B', s:'C'}, loc: "Castle Ensis" },
        { id: 'back', name: "Backhand Blade (DLC)", type: 'Std', bleed: false, dmg: 'Slash', stats:['dex'], scale: {d:'A'}, loc: "Gravesite Plain" },
        { id: 'fiend', name: "Bloodfiend's Arm (DLC)", type: 'Std', bleed: true, dmg: 'Strike', stats:['str','arc'], scale: {a:'S'}, loc: "Prospect Town" },
        { id: 'messmer', name: "Spear of the Impaler", type: 'Somber', bleed: false, dmg: 'Pierce/Fire', skill: "Messmer's Assault", stats:['dex','fai'], scale: {d:'B', f:'C'}, buffable: false, loc: "Messmer Remembrance" },
        { id: 'bayle_kat', name: "Dragon-Hunter's Katana", type: 'Somber', bleed: true, dmg: 'Slash/Pierce', skill: "Dragonwound Slash", stats:['str','dex'], scale: {s:'B', d:'B'}, buffable: false, loc: "Dragon's Pit Boss" },
        { id: 'rellana', name: "Rellana's Twin Blades", type: 'Somber', bleed: false, dmg: 'Magic/Fire', skill: "Moon-and-Fire", stats:['int','fai'], scale: {i:'C', f:'C'}, buffable: false, loc: "Rellana Remembrance" },
        { id: 'solitude', name: "Greatsword of Solitude", type: 'Somber', bleed: false, dmg: 'Standard', skill: "Solitary Moon Slash", stats:['str'], scale: {s:'A'}, buffable: false, loc: "Western Nameless Mausoleum" },
        { id: 'steel', name: "Black Steel Greathammer", type: 'Std', bleed: false, dmg: 'Strike', stats:['str','fai'], scale: {s:'A'}, loc: "Church of Consolation" },
        { id: 'perfume', name: "Lightning Perfume Bottle", type: 'Std', bleed: false, dmg: 'Lightning', stats:['dex','fai'], scale: {d:'C', f:'C'}, loc: "Cerulean Coast" },
        { id: 'anvil', name: "Anvil Hammer", type: 'Somber', bleed: false, dmg: 'Strike/Fire', skill: "Smithing Art Spears", stats:['str','fai'], scale: {s:'B', f:'C'}, buffable: false, loc: "Ruined Forge Lava Intake" },
        { id: 'pata', name: "Pata (DLC)", type: 'Std', bleed: false, dmg: 'Pierce', stats:['dex'], scale: {d:'B'}, loc: "Church of Benediction" },
        { id: 'dryleaf', name: "Dryleaf Arts (DLC)", type: 'Std', bleed: false, dmg: 'Strike', stats:['str','dex'], scale: {s:'C', d:'C'}, loc: "Moorth Ruins" },
        { id: 'dane', name: "Dane's Footwork (DLC)", type: 'Std', bleed: false, dmg: 'Strike', stats:['str','dex'], scale: {s:'C', d:'C'}, loc: "Enir-Ilim (Boss)" },
        { id: 'beast_claw', name: "Beast Claw (DLC)", type: 'Std', bleed: true, dmg: 'Slash', stats:['str','dex'], scale: {s:'C', d:'C'}, loc: "Gravesite Plain Wood" },
        { id: 'falx', name: "Falx (DLC)", type: 'Somber', bleed: true, dmg: 'Slash', skill: "Revenger's Blade", stats:['dex'], scale: {d:'B'}, buffable: false, loc: "Hornsent Questline" },
        { id: 'great_kat', name: "Great Katana (DLC)", type: 'Std', bleed: true, dmg: 'Slash/Pierce', stats:['dex','str'], scale: {d:'C', s:'D'}, loc: "Cerulean Coast (Dragon)" },
        { id: 'star_line', name: "Star-Lined Sword (DLC)", type: 'Somber', bleed: true, dmg: 'Slash/Magic', skill: "Onze's Line of Stars", stats:['dex','int'], scale: {d:'B', i:'D'}, buffable: false, loc: "Demi-Human Queen Marigga" },
        { id: 'putre', name: "Putrescence Cleaver (DLC)", type: 'Somber', bleed: false, dmg: 'Standard/Magic', skill: "Spinning Guillotine", stats:['str','arc'], scale: {s:'C', a:'C'}, buffable: false, loc: "Putrescent Knight Remembrance" },
        { id: 'shadow', name: "Shadow Sunflower Blossom (DLC)", type: 'Somber', bleed: false, dmg: 'Strike/Holy', skill: "Shadow Sunflower Headbutt", stats:['str','fai'], scale: {s:'B', f:'C'}, buffable: false, loc: "Scadutree Avatar Remembrance" },
        { id: 'gaz', name: "Gazing Finger (DLC)", type: 'Somber', bleed: false, dmg: 'Strike/Magic', skill: "Kowtower's Resentment", stats:['str','int'], scale: {s:'C', i:'C'}, buffable: false, loc: "Metyr Remembrance" },
        { id: 'euporia', name: "Euporia (DLC)", type: 'Somber', bleed: false, dmg: 'Standard/Holy', skill: "Euporia Vortex", stats:['fai','dex'], scale: {f:'B', d:'C'}, buffable: false, loc: "Enir-Ilim (Secret Area)" }
    ],
    shields: [
        { id: 'finger', name: "Fingerprint Stone Shield", type: 'Great', loc: "Cathedral of Forsaken" },
        { id: 'brass', name: "Brass Shield", type: 'Med', loc: "Limgrave (Soldier Drop)" },
        { id: 'buckler', name: "Buckler", type: 'Small', loc: "Stormveil (Gostoc)" },
        { id: 'jelly', name: "Jellyfish Shield", type: 'Great', loc: "Liurnia West" },
        { id: 'erdtree', name: "Erdtree Greatshield", type: 'Great', loc: "Altus (Tree Sentinel Duo)" },
        { id: 'turtle', name: "Great Turtle Shell", type: 'Med', loc: "Weeping Peninsula" },
        { id: 'icon', name: "Icon Shield", type: 'Great', loc: "Altus (Woodfolk Ruins)" },
        { id: 'verdigris', name: "Verdigris Shield (DLC)", type: 'Great', loc: "Moore Questline" },
        { id: 'carian', name: "Carian Knight's Shield", type: 'Med', loc: "Raya Lucaria" },
        { id: 'mirror', name: "Silver Mirrorshield", type: 'Med', loc: "Apostate Derelict" },
        { id: 'visage', name: "Visage Shield", type: 'Great', loc: "Caelem Ruins (Boss)" },
        { id: 'one_eye', name: "One-Eyed Shield", type: 'Great', loc: "Guardians' Garrison" },
        { id: 'ant', name: "Ant's Skull Plate", type: 'Great', loc: "Nokstella" },
        { id: 'beast', name: "Beastman's Jar-Shield", type: 'Med', loc: "Azula Beastman Drop" },
        { id: 'coil', name: "Coil Shield", type: 'Small', loc: "Volcano Cave" },
        { id: 'banish', name: "Banished Knight Shield", type: 'Med', loc: "Stormveil (Knight Drop)" },
        { id: 'kite', name: "Kite Shield", type: 'Med', loc: "Liurnia Merchant" },
        { id: 'heater', name: "Heater Shield", type: 'Med', loc: "Roundtable Hold" },
        { id: 'golden', name: "Golden Beast Crest", type: 'Great', loc: "Grafted Scion (Start)" },
        { id: 'eclipse', name: "Eclipse Crest Greatshield", type: 'Great', loc: "Liurnia (Mausoleum Knight)" },
        { id: 'rickety', name: "Rickety Shield", type: 'Small', loc: "Skeleton Drop" },
        { id: 'smold', name: "Smoldering Shield", type: 'Small', loc: "Volcano Manor" },
        { id: 'spiral', name: "Spiralhorn Shield", type: 'Small', loc: "Uld Palace Ruins" },
        { id: 'script', name: "Scripture Wooden Shield", type: 'Small', loc: "Leyndell" },
        { id: 'messmer_s', name: "Messmer Soldier Shield", type: 'Med', loc: "DLC Soldier Drop" },
        { id: 'black_steel', name: "Black Steel Greatshield", type: 'Great', loc: "DLC Black Knight" },
        { id: 'dueling', name: "Dueling Shield (DLC)", type: 'Small', loc: "Shadow Keep" },
        { id: 'thrusting', name: "Carian Thrusting Shield (DLC)", type: 'Med', loc: "Shadow Keep (Storehouse)" }
    ],
    ashes: [
        { id: 'lion', name: "Lion's Claw", loc: "Fort Gael (Caelid)" }, 
        { id: 'unsheathe', name: "Unsheathe", loc: "Limgrave (Scarab)" },
        { id: 'sep', name: "Seppuku", loc: "Freezing Lake" },
        { id: 'crag', name: "Cragblade", loc: "Caelid (Bridge Scarab)" },
        { id: 'flame', name: "Flaming Strike", loc: "Redmane Castle" },
        { id: 'royal', name: "Royal Knight's Resolve", loc: "Volcano Manor" },
        { id: 'ice', name: "Ice Spear", loc: "Liurnia (Night's Cavalry)" },
        { id: 'impale', name: "Impaling Thrust", loc: "Bernahl's Shop" },
        { id: 'spin', name: "Spinning Slash", loc: "Bernahl's Shop" },
        { id: 'pierce', name: "Piercing Fang", loc: "Yura Questline" },
        { id: 'giant', name: "Giant Hunt", loc: "Liurnia (Night's Cavalry)" },
        { id: 'phantom', name: "Phantom Slash", loc: "Forbidden Lands" },
        { id: 'sword', name: "Sword Dance", loc: "Liurnia (Erdtree Avatar)" },
        { id: 'double', name: "Double Slash", loc: "Sellia Town" },
        { id: 'glint', name: "Glintstone Pebble", loc: "Rogier's Shop" },
        { id: 'storm', name: "Storm Blade", loc: "Bernahl's Shop" },
        { id: 'caller', name: "Stormcaller", loc: "Stormveil Castle" },
        { id: 'step', name: "Bloodhound's Step", loc: "Lenne's Rise" },
        { id: 'quick', name: "Quickstep", loc: "Bernahl's Shop" },
        { id: 'grand', name: "Carian Grandeur", loc: "Caria Manor" },
        { id: 'prelate', name: "Prelate's Charge", loc: "Forbidden Lands" },
        { id: 'tornado', name: "Black Flame Tornado", loc: "Godskin Duo" },
        { id: 'waves', name: "Waves of Darkness", loc: "Astel Remembrance" },
        { id: 'hoar', name: "Hoarfrost Stomp", loc: "Liurnia Lake" },
        { id: 'light', name: "Lightning Slash", loc: "Leyndell Capital" },
        { id: 'bolt', name: "Thunderbolt", loc: "Leyndell Capital" },
        { id: 'pray', name: "Prayerful Strike", loc: "Altus (Scarab)" },
        { id: 'gold_vow', name: "Golden Vow (AoW)", loc: "Limgrave (Mounted Knight)" },
        { id: 'erupt', name: "Eruption", loc: "Bernahl's Shop" },
        { id: 'grav', name: "Gravitas", loc: "Limgrave Beach" },
        { id: 'wild', name: "Wild Strikes", loc: "Stormhill Shack" },
        { id: 'roar', name: "Braggart's Roar", loc: "Boggart Drop" },
        { id: 'stamp', name: "Stamp (Upward)", loc: "Bernahl's Shop" },
        { id: 'parry', name: "Parry", loc: "Bernahl's Shop" },
        { id: 'carian', name: "Carian Retaliation", loc: "Pidia's Shop" },
        { id: 'wall', name: "Storm Wall", loc: "Stormhill" },
        { id: 'barr', name: "Barricade Shield", loc: "Weeping Peninsula" },
        { id: 'raptor', name: "Raptor of the Mists", loc: "Yura Questline" },
        { id: 'assassin', name: "Assassin's Gambit", loc: "Volcano Manor" },
        { id: 'lure', name: "White Shadow's Lure", loc: "Consecrated Snowfield" },
        { id: 'life', name: "Lifesteal Fist", loc: "Caelid Highway" },
        { id: 'ground', name: "Ground Slam", loc: "Mistwood" },
        { id: 'kick', name: "Kick", loc: "Bernahl's Shop" },
        { id: 'repeat', name: "Repeating Thrust", loc: "Limgrave (Night's Cav)" },
        { id: 'charge', name: "Charge Forth", loc: "Liurnia Bridge" },
        { id: 'poison', name: "Poisonous Mist", loc: "Aeonia Swamp" },
        { id: 'chill', name: "Chilling Mist", loc: "Ranni's Rise" },
        { id: 'wing', name: "Wing Stance (DLC)", loc: "Castle Ensis" },
        { id: 'savage', name: "Savage Lion's Claw (DLC)", loc: "Gravesite Plain" },
        { id: 'blind', name: "Blind Spot (DLC)", loc: "Gravesite Plain" },
        { id: 'swift', name: "Swift Slash (DLC)", loc: "Hornsent Quest" },
        { id: 'roll', name: "Rolling Sparks (DLC)", loc: "Shadow Keep" },
        { id: 'palm', name: "Palm Blast (DLC)", loc: "Moorth Ruins" }
    ],
    talismans: [
        { id: 'shard', name: "Shard of Alexander", tag: 'skill', loc: "Farum Azula (Alexander Quest)" }, 
        { id: 'blood', name: "Lord of Blood's Exultation", tag: 'bleed', loc: "Leyndell Catacombs" },
        { id: 'rot', name: "Kindred of Rot", tag: 'rot', loc: "Seethewater Cave" }, 
        { id: 'claw', name: "Claw Talisman", tag: 'jump', loc: "Stormveil Castle" },
        { id: 'curved', name: "Curved Sword Talisman", tag: 'guard', loc: "Stormveil Castle" }, 
        { id: 'axe', name: "Axe Talisman", tag: 'charge', loc: "Mistwood Ruins" },
        { id: 'spear', name: "Spear Talisman", tag: 'counter', loc: "Lakeside Crystal Cave" },
        { id: 'hammer', name: "Hammer Talisman", tag: 'stam', loc: "Limgrave (Invader)" },
        { id: 'dagger', name: "Dagger Talisman", tag: 'crit', loc: "Volcano Manor" },
        { id: 'fire', name: "Fire Scorpion Charm", tag: 'fire', loc: "Fort Laiedd" }, 
        { id: 'magic', name: "Magic Scorpion Charm", tag: 'magic', loc: "Seluvis Questline" },
        { id: 'holy', name: "Sacred Scorpion Charm", tag: 'holy', loc: "Anastasia Invader" }, 
        { id: 'light', name: "Lightning Scorpion Charm", tag: 'light', loc: "Wyndham Catacombs" },
        { id: 'rotten', name: "Rotten Winged Sword", tag: 'multi', loc: "Millicent Questline" },
        { id: 'mill', name: "Millicent's Prosthesis", tag: 'multi', loc: "Millicent Questline (Alt)" },
        { id: 'godskin', name: "Godskin Swaddling Cloth", tag: 'heal', loc: "Spiritcaller Cave" },
        { id: 'ritual_s', name: "Ritual Sword Talisman", tag: 'fullhp', loc: "Lux Ruins" },
        { id: 'ritual_d', name: "Ritual Shield Talisman", tag: 'fullhp', loc: "Leyndell Colosseum" },
        { id: 'red', name: "Red-Feathered Branchsword", tag: 'lowhp', loc: "Deathbird (Liurnia)" },
        { id: 'blue', name: "Blue-Feathered Branchsword", tag: 'lowhp', loc: "Deathbird (Limgrave)" },
        { id: 'dragon', name: "Dragoncrest Greatshield", tag: 'def', loc: "Haligtree" },
        { id: 'pearl', name: "Pearldrake Talisman +2", tag: 'def', loc: "Haligtree" },
        { id: 'turtle', name: "Green Turtle Talisman", tag: 'stam', loc: "Summonwater Village" },
        { id: 'amber_h', name: "Crimson Amber +2", tag: 'stat', loc: "Leyndell Ashen Capital" },
        { id: 'amber_f', name: "Cerulean Amber +2", tag: 'stat', loc: "Lunar Estate Ruins" },
        { id: 'amber_s', name: "Viridian Amber +2", tag: 'stat', loc: "Miquella's Haligtree" },
        { id: 'favor', name: "Erdtree's Favor +2", tag: 'stat', loc: "Leyndell Ashen Capital" },
        { id: 'arsenal', name: "Great-Jar's Arsenal", tag: 'equip', loc: "Caelid Colosseum" },
        { id: 'rad_sore', name: "Radagon's Soreseal", tag: 'stat', loc: "Fort Faroth" },
        { id: 'mar_sore', name: "Marika's Soreseal", tag: 'stat', loc: "Elphael" },
        { id: 'bull', name: "Bull-Goat's Talisman", tag: 'poise', loc: "Dragonbarrow Cave" },
        { id: 'godfrey', name: "Godfrey Icon", tag: 'charge', loc: "Golden Lineage Evergaol" },
        { id: 'rad_icon', name: "Radagon Icon", tag: 'cast', loc: "Raya Lucaria Academy" },
        { id: 'flock', name: "Flock's Canvas Talisman", tag: 'incant', loc: "Gowry Questline" },
        { id: 'graven', name: "Graven-Mass Talisman", tag: 'sorc', loc: "Albinauric Rise" },
        { id: 'old', name: "Old Lord's Talisman", tag: 'buff', loc: "Farum Azula" },
        { id: 'carian', name: "Carian Filigreed Crest", tag: 'fp', loc: "Iji (Carial Manor)" },
        { id: 'taker', name: "Taker's Cameo", tag: 'heal', loc: "Volcano Manor Quest" },
        { id: 'ancestor', name: "Ancestral Spirit's Horn", tag: 'fp', loc: "Regal Ancestor Spirit" },
        { id: 'gold', name: "Gold Scarab", tag: 'farm', loc: "Abandoned Cave" },
        { id: 'silver', name: "Silver Scarab", tag: 'farm', loc: "Hidden Path to Haligtree" },
        { id: 'crepus', name: "Crepus's Vial", tag: 'stealth', loc: "Volcano Manor Quest" },
        { id: 'shabriri', name: "Shabriri's Woe", tag: 'aggro', loc: "Frenzy-Flaming Village" },
        { id: 'cat', name: "Longtail Cat Talisman", tag: 'util', loc: "Raya Lucaria Academy" },
        { id: 'star_h', name: "Starscourge Heirloom", tag: 'stat', loc: "Fort Gael" },
        { id: 'pros_h', name: "Prosthesis-Wearer Heirloom", tag: 'stat', loc: "Gowry Questline" },
        { id: 'gazer', name: "Stargazer Heirloom", tag: 'stat', loc: "Divine Tower of Liurnia" },
        { id: 'finger', name: "Two Fingers Heirloom", tag: 'stat', loc: "Purified Ruins" },
        { id: 'blue_dance', name: "Blue Dancer Charm", tag: 'naked', loc: "Highroad Cave" },
        { id: 'crusade', name: "Crusade Insignia (DLC)", tag: 'heal', loc: "Belurat Tower" },
        { id: 'braid', name: "Golden Braid (DLC)", tag: 'def', loc: "Shaman Village" },
        { id: 'two_head', name: "Two-Headed Turtle (DLC)", tag: 'stam', loc: "Rivermouth Cave" },
        { id: 'smith', name: "Smithing Talisman (DLC)", tag: 'throw', loc: "Ruined Forge" },
        { id: 'blade', name: "Blade of Mercy (DLC)", tag: 'crit', loc: "Scorched Ruins" },
        { id: 'dried', name: "Dried Bouquet (DLC)", tag: 'sum', loc: "Belurat" },
        { id: 'enrage', name: "Enraged Divine Beast (DLC)", tag: 'storm', loc: "Lion Boss Reward" },
        { id: 'shat', name: "Shattered Stone (DLC)", tag: 'kick', loc: "Moorth Ruins" },
        { id: 'aim', name: "Arrow's Soaring Sting (DLC)", tag: 'bow', loc: "Fog Rift Fort" },
        { id: 'talisman_dread', name: "Talisman of the Dread (DLC)", tag: 'magma', loc: "Elder's Hovel" }
    ],
    buffs: [
        { id: 'vow', name: "Golden Vow (Spell)", loc: "Mt Gelmir" },
        { id: 'fgms', name: "Flame, Grant Me Strength", loc: "Caelid" },
        { id: 'terra', name: "Terra Magica", loc: "Academy Crystal Cave" },
        { id: 'shab', name: "Howl of Shabriri", loc: "Frenzy Tower" },
        { id: 'bloodflame', name: "Bloodflame Blade", loc: "Liurnia" },
        { id: 'blackflame', name: "Black Flame's Protection", loc: "Roundtable" },
        { id: 'electrify', name: "Electrify Armament", loc: "Liurnia" },
        { id: 'order', name: "Order's Blade", loc: "Roundtable" },
        { id: 'poison_w', name: "Poison Armament", loc: "Caelid" },
        { id: 'frozen', name: "Frozen Armament", loc: "Caria Manor" },
        { id: 'scholars', name: "Scholar's Armament", loc: "Sellen's Shop" },
        { id: 'vyke_drag', name: "Vyke's Dragonbolt", loc: "Lord Contender's Evergaol" },
        { id: 'protect', name: "Protection of the Erdtree", loc: "Altus Plateau" },
        { id: 'barrier', name: "Barrier of Gold", loc: "Leyndell" },
        { id: 'lord', name: "Lord's Divine Fortification", loc: "Roundtable" },
        { id: 'flame_p', name: "Flame, Protect Me", loc: "Giant-Conquering Hero's Grave" }
    ],
    greases: [
        { id: 'fire', name: "Fire Grease" }, { id: 'magic', name: "Magic Grease" },
        { id: 'blood', name: "Blood Grease" }, { id: 'rot', name: "Rot Grease" },
        { id: 'freeze', name: "Freezing Grease" }, { id: 'light', name: "Lightning Grease" },
        { id: 'holy', name: "Holy Grease" }, { id: 'sleep', name: "Soporific Grease" },
        { id: 'poison', name: "Poison Grease" }, { id: 'dragon', name: "Dragonwound Grease" },
        { id: 'shield', name: "Shield Grease" }
    ],
    bosses: [
        { id: 'malenia', name: 'Malenia', weak: ['Fire', 'Bleed', 'Frost', 'Stagger'], resist: ['Holy', 'Rot'], tip: 'Weak to stagger. Use Frost Pots for Waterfowl.' },
        { id: 'radagon', name: 'Radagon', weak: ['Fire', 'Strike'], resist: ['Holy', 'Bleed'], tip: 'Immune to bleed. Strike damage works best.' },
        { id: 'elden', name: 'Elden Beast', weak: ['Physical'], resist: ['Holy', 'Status'], tip: 'Target the chest scar. Use Pest Threads or Black Flame.' },
        { id: 'mohg', name: 'Mohg', weak: ['Bleed'], resist: ['Fire'], tip: 'Purifying Crystal Tear is mandatory.' },
        { id: 'maliketh', name: 'Maliketh', weak: ['Physical'], resist: ['Holy'], tip: 'Low HP. Use Blasphemous Claw.' },
        { id: 'godskin', name: 'Godskin Duo', weak: ['Sleep', 'Bleed', 'Slash'], resist: ['Holy', 'Fire'], tip: 'Throw Sleep Pots to isolate 1v1.' },
        { id: 'rykard', name: 'Rykard', weak: ['Serpent'], resist: ['Fire'], tip: 'Must use Serpent-Hunter spear.' },
        { id: 'giant', name: 'Fire Giant', weak: ['Slash', 'Bleed'], resist: ['Fire'], tip: 'Attack the unarmored ankle, then hands.' },
        { id: 'placid', name: 'Placidusax', weak: ['Pierce'], resist: ['Status'], tip: 'Ancient Dragon. Use Pierce damage to tail.' },
        { id: 'tree', name: 'Draconic Tree Sentinel', weak: ['Strike', 'Rot'], resist: ['Lightning'], tip: 'Use Rotten Stray or Strike weapons.' },
        { id: 'messmer', name: 'Messmer (DLC)', weak: ['Bleed', 'Frost', 'Slash'], resist: ['Fire'], tip: 'Resists Fire. Punish snake attacks.' },
        { id: 'radahn_dlc', name: 'Consort Radahn (DLC)', weak: ['Pierce', 'Rot', 'Bleed'], resist: ['Holy', 'Slash'], tip: 'Use Greatshield + Poke weapon.' },
        { id: 'rellana', name: 'Rellana (DLC)', weak: ['Lightning', 'Pierce'], resist: ['Magic', 'Fire'], tip: 'Parry her. Jump moon moons.' },
        { id: 'bayle', name: 'Bayle (DLC)', weak: ['Dragon'], resist: ['Lightning', 'Fire'], tip: 'Use Dragon-Hunter Katana skill.' },
        { id: 'midra', name: 'Midra (DLC)', weak: ['Bleed', 'Slash'], resist: ['Fire'], tip: 'Very low poise. Stagger him.' },
        { id: 'gaius', name: 'Gaius (DLC)', weak: ['Holy', 'Lightning'], resist: ['Physical'], tip: 'Dodge INTO charge. Use Holy.' },
        { id: 'scadu', name: 'Scadutree Avatar (DLC)', weak: ['Fire'], resist: ['Holy'], tip: 'Hit the head (flower). Use Fire.' },
        { id: 'hippo', name: 'Golden Hippo (DLC)', weak: ['Lightning', 'Slash'], resist: ['Holy'], tip: 'Use Lightning. Hit head.' },
        { id: 'romina', name: 'Romina (DLC)', weak: ['Bleed', 'Frost'], resist: ['Rot'], tip: 'Fast attacks. Use Bleed.' },
        { id: 'lion', name: 'Dancing Lion (DLC)', weak: ['Fire', 'Pierce'], resist: ['Holy'], tip: 'Weak to Pierce. Don\'t lock on under him.' },
        { id: 'putre', name: "Putrescent Knight (DLC)", weak: ['Holy', 'Fire'], resist: ['Poison'], tip: 'Jump the blue flames.' },
        { id: 'metyr', name: "Metyr, Mother of Fingers (DLC)", weak: ['Bleed', 'Frost'], resist: ['Magic'], tip: 'Hit the fleshy parts.' },
        { id: 'night', name: "Night's Cavalry", weak: ['Lightning', 'Strike'], resist: ['Slash'], tip: 'Knock off horse for instant crit.' },
        { id: 'bird', name: "Death Rite Bird", weak: ['Holy', 'Strike'], resist: ['Magic'], tip: 'Extremely weak to Holy Pots.' },
        { id: 'bell', name: "Bell Bearing Hunter", weak: ['Pierce', 'Lightning'], resist: ['Slash'], tip: 'Parry him. Do not heal far away.' },
        { id: 'watch', name: "Erdtree Watchdog", weak: ['Strike'], resist: ['Magic', 'Slash'], tip: 'Use Crystal Darts to glitch them.' },
        { id: 'garg', name: "Valiant Gargoyles", weak: ['Strike', 'Magic'], resist: ['Slash', 'Fire'], tip: 'Immune to status. Use Magic/Strike.' },
        { id: 'astel', name: "Astel, Naturalborn", weak: ['Physical'], resist: ['Magic', 'Elemental'], tip: 'Hit the head. Use Gravity stones.' },
        { id: 'rennala', name: "Rennala", weak: ['Physical', 'Bleed'], resist: ['Magic'], tip: 'Stagger her constantly.' },
        { id: 'ancestor', name: "Regal Ancestor Spirit", weak: ['Fire', 'Holy'], resist: ['Magic'], tip: 'Passive fight. Use Fire.' },
        { id: 'fortissax', name: "Lichdragon Fortissax", weak: ['Pierce'], resist: ['Lightning', 'Holy'], tip: 'Hit head/legs. Avoid death blight.' },
        { id: 'margit', name: "Margit/Morgott", weak: ['Slash', 'Bleed'], resist: ['Holy'], tip: 'Use Margit\'s Shackle.' }
    ],
    affinities: [
        { id: 'std', name: 'Standard', canBuff: true, desc: "Default scaling." }, { id: 'heavy', name: 'Heavy', canBuff: true, desc: "Str scaling." }, 
        { id: 'keen', name: 'Keen', canBuff: true, desc: "Dex scaling." }, { id: 'qual', name: 'Quality', canBuff: true, desc: "Str/Dex scaling." }, 
        { id: 'magic', name: 'Magic', type:'Magic', canBuff: false, desc: "Int scaling." }, { id: 'fire', name: 'Fire', type:'Fire', canBuff: false, desc: "Str scaling." },
        { id: 'flame', name: 'Flame Art', type:'Fire', canBuff: false, desc: "Fai scaling." }, { id: 'light', name: 'Lightning', type:'Lightning', canBuff: false, desc: "Dex scaling." },
        { id: 'sacred', name: 'Sacred', type:'Holy', canBuff: false, desc: "Fai scaling." }, { id: 'blood', name: 'Blood', type:'Phys', effect:'Bleed', canBuff: false, desc: "Arc scaling + Bleed." },
        { id: 'occult', name: 'Occult', type:'Phys', canBuff: false, desc: "Arc scaling." }, { id: 'cold', name: 'Cold', type:'Magic', effect:'Frost', canBuff: false, desc: "Int scaling + Frost." }
    ]
};
