const DB = {
    weapons: [
        // SOMBER
        { id: 'rob', name: "Rivers of Blood", type: 'Somber', bleed: true, dmg: 'Slash/Fire', skill: "Corpse Piler", stats:['dex','arc'], scale: {d:'B', a:'D'}, buffable: false, loc: "Mountaintops (Church of Repose)" },
        { id: 'moon', name: "Moonveil", type: 'Somber', bleed: true, dmg: 'Slash/Magic', skill: "Transient Moonlight", stats:['dex','int'], scale: {d:'B', i:'B'}, buffable: false, loc: "Caelid (Gael Tunnel)" },
        { id: 'blas', name: "Blasphemous Blade", type: 'Somber', bleed: false, dmg: 'Standard/Fire', skill: "Taker's Flames", stats:['str','fai'], scale: {s:'C', f:'B'}, buffable: false, loc: "Volcano Manor (Rykard Rem.)" },
        { id: 'fang', name: "Bloodhound's Fang", type: 'Somber', bleed: true, dmg: 'Slash', skill: "Bloodhound's Finesse", stats:['dex','str'], scale: {d:'B', s:'C'}, buffable: true, loc: "Limgrave (Forlorn Hound Evergaol)" },
        { id: 'ruins', name: "Ruins Greatsword", type: 'Somber', bleed: false, dmg: 'Standard/Magic', skill: "Wave of Destruction", stats:['str'], scale: {s:'S'}, buffable: false, loc: "Redmane Castle Plaza" },
        { id: 'mohg', name: "Mohgwyn's Spear", type: 'Somber', bleed: true, dmg: 'Pierce/Fire', skill: "Bloodboon Ritual", stats:['str','arc'], scale: {a:'C', s:'C'}, buffable: false, loc: "Mohgwyn Palace (Mohg Rem.)" },
        { id: 'dark', name: "Dark Moon Greatsword", type: 'Somber', bleed: false, dmg: 'Standard/Magic', skill: "Moonlight Greatsword", stats:['int','str'], scale: {i:'B'}, buffable: false, loc: "Liurnia (Ranni Quest)" },
        { id: 'bolt', name: "Bolt of Gransax", type: 'Somber', bleed: false, dmg: 'Pierce/Lightning', skill: "Ancient Lightning Spear", stats:['dex'], scale: {d:'B'}, buffable: false, loc: "Leyndell Capital" },
        { id: 'morgott', name: "Morgott's Cursed Sword", type: 'Somber', bleed: true, dmg: 'Slash/Fire', skill: "Cursed-Blood Slice", stats:['dex','arc'], scale: {d:'B', a:'D'}, buffable: false, loc: "Leyndell (Morgott Rem.)" },
        { id: 'godslayer', name: "Godslayer's Greatsword", type: 'Somber', bleed: false, dmg: 'Standard/Fire', skill: "Queen's Black Flame", stats:['dex','fai'], scale: {d:'B', f:'C'}, buffable: false, loc: "Caelid (Divine Tower)" },
        { id: 'black_knife', name: "Black Knife", type: 'Somber', bleed: false, dmg: 'Slash/Holy', skill: "Blade of Death", stats:['dex','fai'], scale: {f:'B'}, buffable: false, loc: "Altus (Sainted Hero's Grave)" },
        { id: 'vyke', name: "Vyke's War Spear", type: 'Somber', bleed: false, dmg: 'Pierce/Fire', skill: "Frenzyflame Thrust", stats:['dex','fai'], scale: {d:'B', f:'C'}, buffable: false, loc: "Liurnia (Invader)" },
        { id: 'wing', name: "Wing of Astel", type: 'Somber', bleed: false, dmg: 'Slash/Magic', skill: "Nebula", stats:['int','dex'], scale: {i:'B'}, buffable: false, loc: "Ainsel River" },
        { id: 'ordovis', name: "Ordovis's Greatsword", type: 'Somber', bleed: false, dmg: 'Standard/Holy', skill: "Ordovis's Vortex", stats:['str','fai'], scale: {s:'A', f:'C'}, buffable: false, loc: "Altus (Auriza Hero's Grave)" },
        { id: 'eleonora', name: "Eleonora's Poleblade", type: 'Somber', bleed: true, dmg: 'Standard/Fire', skill: "Bloodblade Dance", stats:['dex','arc'], scale: {d:'C', a:'D'}, buffable: false, loc: "Altus (Second Church)" },
        { id: 'maliketh_b', name: "Maliketh's Black Blade", type: 'Somber', bleed: false, dmg: 'Standard/Holy', skill: "Destined Death", stats:['str','fai'], scale: {s:'B', f:'B'}, buffable: false, loc: "Farum Azula (Maliketh Rem.)" },
        { id: 'radahn_s', name: "Starscourge Greatsword", type: 'Somber', bleed: false, dmg: 'Standard/Magic', skill: "Starcaller Cry", stats:['str'], scale: {s:'B'}, buffable: false, loc: "Caelid (Radahn Rem.)" },
        { id: 'magma', name: "Magma Wyrm's Scalesword", type: 'Somber', bleed: false, dmg: 'Slash/Fire', skill: "Magma Guillotine", stats:['str','fai'], scale: {s:'B', f:'B'}, buffable: false, loc: "Ruin-Strewn Precipice" },
        { id: 'golden_order', name: "Golden Order Greatsword", type: 'Somber', bleed: false, dmg: 'Standard/Holy', skill: "Establish Order", stats:['fai','dex'], scale: {f:'B'}, buffable: false, loc: "Cave of the Forlorn" },
        { id: 'reduvia', name: "Reduvia", type: 'Somber', bleed: true, dmg: 'Slash', skill: "Reduvia Blood Blade", stats:['arc','dex'], scale: {a:'C'}, buffable: false, loc: "Limgrave (Invader Nerijus)" },
        
        // STANDARD WEAPONS
        { id: 'guts', name: "Greatsword (Guts)", type: 'Std', bleed: false, dmg: 'Standard', stats:['str'], scale: {s:'A'}, loc: "Caelid (Dragonbarrow Caravan)" },
        { id: 'naga', name: "Nagakiba", type: 'Std', bleed: true, dmg: 'Slash/Pierce', stats:['dex'], scale: {d:'A'}, loc: "Limgrave/Altus (Yura Quest)" },
        { id: 'uchi', name: "Uchigatana", type: 'Std', bleed: true, dmg: 'Slash/Pierce', stats:['dex'], scale: {d:'B'}, loc: "Limgrave (Catacombs)" },
        { id: 'clay', name: "Claymore", type: 'Std', bleed: false, dmg: 'Standard/Pierce', stats:['str','dex'], scale: {s:'C', d:'C'}, loc: "Weeping Peninsula (Castle Morne)" },
        { id: 'zwei', name: "Zweihander", type: 'Std', bleed: false, dmg: 'Standard/Pierce', stats:['dex','str'], scale: {d:'B', s:'C'}, loc: "Weeping Peninsula (Merchant)" },
        { id: 'giant', name: "Giant-Crusher", type: 'Std', bleed: false, dmg: 'Strike', stats:['str'], scale: {s:'S'}, loc: "Altus (Outer Wall Caravan)" },
        { id: 'star', name: "Star Fist", type: 'Std', bleed: true, dmg: 'Strike', stats:['str'], scale: {s:'A'}, loc: "Leyndell (Colosseum)" },
        { id: 'scav', name: "Scavenger's Curved Sword", type: 'Std', bleed: true, dmg: 'Slash', stats:['dex'], scale: {d:'C'}, loc: "Mt Gelmir" },
        { id: 'peel', name: "Godskin Peeler", type: 'Std', bleed: false, dmg: 'Standard', stats:['dex'], scale: {d:'A'}, loc: "Altus (Windmill Village)" },
        { id: 'cross', name: "Cross-Naginata", type: 'Std', bleed: true, dmg: 'Pierce', stats:['dex'], scale: {d:'B'}, loc: "Caelid (Gael Tunnel)" },
        { id: 'night', name: "Nightrider Glaive", type: 'Std', bleed: false, dmg: 'Slash', stats:['str'], scale: {s:'S'}, loc: "Liurnia (Night's Cavalry)" },
        { id: 'mace', name: "Great Mace", type: 'Std', bleed: false, dmg: 'Strike', stats:['str'], scale: {s:'A'}, loc: "Liurnia (Dectus Lift)" },
        { id: 'ant', name: "Antspur Rapier", type: 'Std', bleed: false, dmg: 'Pierce', stats:['dex'], scale: {d:'C'}, loc: "Altus (Maleigh Marais)" },
        { id: 'hook', name: "Hookclaws", type: 'Std', bleed: true, dmg: 'Slash', stats:['dex'], scale: {d:'B'}, loc: "Stormveil Castle" },
        { id: 'grave', name: "Grave Scythe", type: 'Std', bleed: true, dmg: 'Slash', stats:['str','dex'], scale: {s:'C', d:'C'}, loc: "Liurnia (Skeleton Mage Drop)" },
        { id: 'exe', name: "Executioner's Greataxe", type: 'Std', bleed: false, dmg: 'Standard', stats:['str'], scale: {s:'A'}, loc: "Liurnia (Skeleton Drop)" },
        { id: 'lance', name: "Lance", type: 'Std', bleed: false, dmg: 'Pierce', stats:['str'], scale: {s:'B'}, loc: "Limgrave (Deathtouched Catacombs Top)" },
        { id: 'broad', name: "Broadsword", type: 'Std', bleed: false, dmg: 'Standard', stats:['str'], scale: {s:'C'}, loc: "Limgrave (Merchant)" },
        { id: 'bandit', name: "Bandit's Curved Sword", type: 'Std', bleed: false, dmg: 'Slash', stats:['str','dex'], scale: {d:'C'}, loc: "Weeping Peninsula (Skeleton Drop)" },
        { id: 'rogiers', name: "Rogier's Rapier", type: 'Std', bleed: false, dmg: 'Pierce', stats:['dex'], scale: {d:'B'}, loc: "Roundtable (Rogier)" },
        { id: 'pike', name: "Pike", type: 'Std', bleed: false, dmg: 'Pierce', stats:['str'], scale: {s:'C'}, loc: "Stormveil Castle" },
        { id: 'morning', name: "Morning Star", type: 'Std', bleed: true, dmg: 'Strike', stats:['str'], scale: {s:'C'}, loc: "Weeping Peninsula" },
        
        // DLC WEAPONS
        { id: 'milady', name: "Milady (DLC)", type: 'Std', bleed: false, dmg: 'Standard/Pierce', stats:['dex'], scale: {d:'B', s:'C'}, loc: "Castle Ensis" },
        { id: 'back', name: "Backhand Blade (DLC)", type: 'Std', bleed: false, dmg: 'Slash', stats:['dex'], scale: {d:'A'}, loc: "Gravesite Plain" },
        { id: 'fiend', name: "Bloodfiend's Arm (DLC)", type: 'Std', bleed: true, dmg: 'Strike', stats:['str','arc'], scale: {a:'S'}, loc: "Prospect Town" },
        { id: 'messmer', name: "Spear of the Impaler", type: 'Somber', bleed: false, dmg: 'Pierce/Fire', skill: "Messmer's Assault", stats:['dex','fai'], scale: {d:'B', f:'C'}, buffable: false, loc: "Messmer Remembrance" },
        { id: 'bayle_kat', name: "Dragon-Hunter's Katana", type: 'Somber', bleed: true, dmg: 'Slash/Pierce', skill: "Dragonwound Slash", stats:['str','dex'], scale: {s:'B', d:'B'}, buffable: false, loc: "Dragon's Pit Boss" },
        { id: 'rellana', name: "Rellana's Twin Blades", type: 'Somber', bleed: false, dmg: 'Magic/Fire', skill: "Moon-and-Fire", stats:['int','fai'], scale: {i:'C', f:'C'}, buffable: false, loc: "Rellana Remembrance" },
        { id: 'solitude', name: "Greatsword of Solitude", type: 'Somber', bleed: false, dmg: 'Standard', skill: "Solitary Moon Slash", stats:['str'], scale: {s:'A'}, buffable: false, loc: "Western Nameless Mausoleum" },
        { id: 'steel', name: "Black Steel Greathammer", type: 'Std', bleed: false, dmg: 'Strike', stats:['str','fai'], scale: {s:'A'}, loc: "Church of Consolation" },
        { id: 'perfume', name: "Lightning Perfume Bottle", type: 'Std', bleed: false, dmg: 'Lightning', stats:['dex','fai'], scale: {d:'C', f:'C'}, loc: "Cerulean Coast" },
        { id: 'anvil', name: "Anvil Hammer", type: 'Somber', bleed: false, dmg: 'Strike/Fire', skill: "Smithing Art Spears", stats:['str','fai'], scale: {s:'B', f:'C'}, buffable: false, loc: "Ruined Forge Lava Intake" },
        { id: 'pata', name: "Pata (DLC)", type: 'Std', bleed: false, dmg: 'Pierce', stats:['dex'], scale: {d:'B'}, loc: "Church of Benediction" },
        { id: 'dryleaf', name: "Dryleaf Arts (DLC)", type: 'Std', bleed: false, dmg: 'Strike', stats:['str','dex'], scale: {s:'C', d:'C'}, loc: "Moorth Ruins" },
        { id: 'beast_claw', name: "Beast Claw (DLC)", type: 'Std', bleed: true, dmg: 'Slash', stats:['str','dex'], scale: {s:'C', d:'C'}, loc: "Gravesite Plain Wood" },
        { id: 'falx', name: "Falx (DLC)", type: 'Somber', bleed: true, dmg: 'Slash', skill: "Revenger's Blade", stats:['dex'], scale: {d:'B'}, buffable: false, loc: "Hornsent Questline" }
    ],
    shields: [
        { id: 'finger', name: "Fingerprint Stone Shield", type: 'Great', desc: "Heaviest shield with highest guard boost. Almost impenetrable.", loc: "Cathedral of Forsaken" },
        { id: 'brass', name: "Brass Shield", type: 'Med', desc: "Best medium shield. No skill, allowing weapon skill use.", loc: "Limgrave (Soldier Drop)" },
        { id: 'buckler', name: "Buckler", type: 'Small', desc: "Has unique 'Buckler Parry' with best parry frames.", loc: "Stormveil (Gostoc)" },
        { id: 'jelly', name: "Jellyfish Shield", type: 'Great', desc: "Skill boosts all damage by 20%. Cannot block while buffed.", loc: "Liurnia West" },
        { id: 'erdtree', name: "Erdtree Greatshield", type: 'Great', desc: "Reflects magic spells back at enemies.", loc: "Altus (Tree Sentinel Duo)" },
        { id: 'turtle', name: "Great Turtle Shell", type: 'Med', desc: "Passively boosts stamina recovery.", loc: "Weeping Peninsula" },
        { id: 'icon', name: "Icon Shield", type: 'Great', desc: "Passively heals HP over time.", loc: "Altus (Woodfolk Ruins)" },
        { id: 'verdigris', name: "Verdigris Shield (DLC)", type: 'Great', desc: "Highest guard boost in DLC. Absolute tank.", loc: "Moore Questline" },
        { id: 'carian', name: "Carian Knight's Shield", type: 'Med', desc: "High magic negation. Good for mages.", loc: "Raya Lucaria" },
        { id: 'mirror', name: "Silver Mirrorshield", type: 'Med', desc: "Highest magic negation of any medium shield.", loc: "Apostate Derelict" },
        { id: 'visage', name: "Visage Shield", type: 'Great', desc: "Flamethrower skill. Good guard boost.", loc: "Caelem Ruins" },
        { id: 'one_eye', name: "One-Eyed Shield", type: 'Great', desc: "Cannon skill. Shoots explosive fireball.", loc: "Guardians' Garrison" },
        { id: 'ant', name: "Ant's Skull Plate", type: 'Great', desc: "High hardness causes attacks to bounce.", loc: "Nokstella" },
        { id: 'beast', name: "Beastman's Jar-Shield", type: 'Med', desc: "Lightweight with decent guard.", loc: "Azula Beastman Drop" },
        { id: 'coil', name: "Coil Shield", type: 'Small', desc: "Inflicts deadly poison (venom).", loc: "Volcano Cave" },
        { id: 'banish', name: "Banished Knight Shield", type: 'Med', desc: "High stability medium shield.", loc: "Stormveil" },
        { id: 'kite', name: "Kite Shield", type: 'Med', desc: "Standard knight shield.", loc: "Liurnia Merchant" },
        { id: 'heater', name: "Heater Shield", type: 'Med', desc: "Lightest 100% phys block shield.", loc: "Roundtable Hold" },
        { id: 'golden', name: "Golden Beast Crest", type: 'Great', desc: "Good early game greatshield.", loc: "Grafted Scion (Start)" },
        { id: 'eclipse', name: "Eclipse Crest Greatshield", type: 'Great', desc: "Boosts Immunity, Robustness, Focus.", loc: "Liurnia" },
        { id: 'rickety', name: "Rickety Shield", type: 'Small', desc: "Very light.", loc: "Skeleton Drop" },
        { id: 'smold', name: "Smoldering Shield", type: 'Small', desc: "Shield Bash causes fire damage.", loc: "Volcano Manor" },
        { id: 'spiral', name: "Spiralhorn Shield", type: 'Small', desc: "Boosts Immunity, Robustness, Focus.", loc: "Uld Palace Ruins" },
        { id: 'script', name: "Scripture Wooden Shield", type: 'Small', desc: "Lightest shield.", loc: "Leyndell" },
        { id: 'messmer_s', name: "Messmer Soldier Shield", type: 'Med', desc: "Good guard boost for weight.", loc: "DLC Soldier Drop" },
        { id: 'black_steel', name: "Black Steel Greatshield", type: 'Great', desc: "High Holy negation. Heavy.", loc: "DLC Black Knight" }
    ],
    ashes: [
        { id: 'lion', name: "Lion's Claw", type: 'Phys', desc: "Somersault slam. Huge hyper armor & stance dmg.", loc: "Fort Gael (Caelid)" }, 
        { id: 'unsheathe', name: "Unsheathe", type: 'Phys', desc: "Fast katana stance. High poise damage.", loc: "Limgrave (Scarab)" },
        { id: 'sep', name: "Seppuku", type: 'Phys', desc: "Massive bleed buff at cost of HP.", loc: "Freezing Lake" },
        { id: 'crag', name: "Cragblade", type: 'Phys', desc: "Buffs weapon Physical Dmg & Stance Dmg.", loc: "Caelid (Bridge Scarab)" },
        { id: 'flame', name: "Flaming Strike", type: 'Fire', desc: "Fire arc + heavy attack buffs weapon with Fire.", loc: "Redmane Castle" },
        { id: 'royal', name: "Royal Knight's Resolve", type: 'Phys', desc: "+80% damage on next hit.", loc: "Volcano Manor" },
        { id: 'ice', name: "Ice Spear", type: 'Magic', desc: "Ranged frost projectile. Staggers well.", loc: "Liurnia (Night's Cavalry)" },
        { id: 'impale', name: "Impaling Thrust", type: 'Phys', desc: "Quick shield-piercing thrust.", loc: "Bernahl's Shop" },
        { id: 'spin', name: "Spinning Slash", type: 'Phys', desc: "Fast spin combo. Excellent for status.", loc: "Bernahl's Shop" },
        { id: 'pierce', name: "Piercing Fang", type: 'Phys', desc: "Lunging thrust. Ignores shields entirely.", loc: "Yura Questline" },
        { id: 'giant', name: "Giant Hunt", type: 'Phys', desc: "Launches foes into air. Great roll catch.", loc: "Liurnia (Night's Cavalry)" },
        { id: 'phantom', name: "Phantom Slash", type: 'Phys', desc: "Summons phantom for range + gap close.", loc: "Forbidden Lands" },
        { id: 'sword', name: "Sword Dance", type: 'Phys', desc: "Rapid gap closing combo. Good roll catch.", loc: "Liurnia (Erdtree Avatar)" },
        { id: 'double', name: "Double Slash", type: 'Phys', desc: "Genichiro combo. Great on Nagakiba with Bloodflame.", loc: "Sellia Town" },
        { id: 'glint', name: "Glintstone Pebble", type: 'Magic', desc: "Magic dart + thrust combo. True combo in PvP.", loc: "Rogier's Shop" },
        { id: 'storm', name: "Storm Blade", type: 'Phys', desc: "Ranged wind projectile. Spammable.", loc: "Bernahl's Shop" },
        { id: 'caller', name: "Stormcaller", type: 'Phys', desc: "Traps enemies in wind storm. True combo.", loc: "Stormveil Castle" },
        { id: 'step', name: "Bloodhound's Step", type: 'Phys', desc: "Invisible dodge. High i-frames.", loc: "Lenne's Rise" },
        { id: 'quick', name: "Quickstep", type: 'Phys', desc: "Fast dodge. Good for backstabs.", loc: "Bernahl's Shop" },
        { id: 'grandeur', name: "Carian Grandeur", type: 'Magic', desc: "Chargeable magic sword. Nuclear damage.", loc: "Caria Manor" },
        { id: 'prelate', name: "Prelate's Charge", type: 'Fire', desc: "Run forward with fire. Stunlocks enemies.", loc: "Forbidden Lands" },
        { id: 'tornado', name: "Black Flame Tornado", type: 'Fire', desc: "Melts bosses with % HP damage.", loc: "Godskin Duo" },
        { id: 'waves', name: "Waves of Darkness", type: 'Magic', desc: "3-hit gravity AoE. Hyper armor.", loc: "Astel Remembrance" },
        { id: 'hoar', name: "Hoarfrost Stomp", type: 'Magic', desc: "Cone frost AoE. Fast cast.", loc: "Liurnia Lake" },
        { id: 'light', name: "Lightning Slash", type: 'Lightning', desc: "Lightning strike + buffs weapon.", loc: "Leyndell Capital" },
        { id: 'bolt', name: "Thunderbolt", type: 'Lightning', desc: "Ranged lightning strike from above.", loc: "Leyndell Capital" },
        { id: 'pray', name: "Prayerful Strike", type: 'Holy', desc: "Slow slam that heals 30% HP on hit.", loc: "Altus (Scarab)" },
        { id: 'gold_vow', name: "Golden Vow (AoW)", type: 'Holy', desc: "Buffs Atk & Def for self and allies.", loc: "Limgrave (Mounted Knight)" },
        { id: 'erupt', name: "Eruption", type: 'Fire', desc: "Lava slam. Leaves lava pool.", loc: "Bernahl's Shop" },
        { id: 'grav', name: "Gravitas", type: 'Magic', desc: "Pulls enemies in. Good for flying mobs.", loc: "Limgrave Beach" },
        { id: 'wild', name: "Wild Strikes", type: 'Phys', desc: "Continuous swinging. High poise.", loc: "Stormhill Shack" },
        { id: 'roar', name: "Braggart's Roar", type: 'Phys', desc: "Buffs Atk, Def, and Stamina recovery.", loc: "Boggart Drop" },
        { id: 'stamp', name: "Stamp (Upward Cut)", type: 'Phys', desc: "Tanks hit then launches enemy.", loc: "Bernahl's Shop" },
        { id: 'parry', name: "Parry", type: 'Phys', desc: "Deflects attacks to allow critical hit.", loc: "Bernahl's Shop" },
        { id: 'carian', name: "Carian Retaliation", type: 'Magic', desc: "Parries spells and turns them into glintblades.", loc: "Pidia's Shop" },
        { id: 'wall', name: "Storm Wall", type: 'Phys', desc: "Parries attacks and deflects arrows.", loc: "Stormhill" },
        { id: 'bash', name: "Shield Bash", type: 'Phys', desc: "Attack while blocking. Uninterruptible.", loc: "Bernahl's Shop" },
        { id: 'barr', name: "Barricade Shield", type: 'Phys', desc: "Temporarily boosts shield hardness/guard.", loc: "Weeping Peninsula" },
        { id: 'raptor', name: "Raptor of the Mists", type: 'Phys', desc: "Jump into air when hit. Good vs chariots.", loc: "Yura Questline" },
        { id: 'assassin', name: "Assassin's Gambit", type: 'Phys', desc: "Self-harm to become nearly invisible.", loc: "Volcano Manor (Bernahl)" },
        { id: 'lure', name: "White Shadow's Lure", type: 'Phys', desc: "Distracts humanoids/beasts.", loc: "Consecrated Snowfield" },
        { id: 'life', name: "Lifesteal Fist", type: 'Magic', desc: "Grabs humanoids, steals HP/FP.", loc: "Caelid Highway" },
        { id: 'ground', name: "Ground Slam", type: 'Phys', desc: "Butt slam. AoE shockwave.", loc: "Mistwood" },
        { id: 'kick', name: "Kick", type: 'Phys', desc: "Instantly breaks guard of shielded enemies.", loc: "Bernahl's Shop" },
        { id: 'repeat', name: "Repeating Thrust", type: 'Phys', desc: "Rapid flurry of thrusts. Good for rot.", loc: "Limgrave (Night's Cav)" },
        { id: 'charge', name: "Charge Forth", type: 'Phys', desc: "Long distance charge attack.", loc: "Liurnia Bridge" },
        { id: 'poison', name: "Poisonous Mist", type: 'Phys', desc: "Releases poison cloud. Hits through walls.", loc: "Aeonia Swamp" },
        { id: 'chill', name: "Chilling Mist", type: 'Magic', desc: "Releases frost cloud + buffs weapon.", loc: "Ranni's Rise" },
        { id: 'wing', name: "Wing Stance (DLC)", type: 'Phys', desc: "Elegant combo stance.", loc: "Castle Ensis" },
        { id: 'savage', name: "Savage Lion's Claw (DLC)", type: 'Phys', desc: "Lion's Claw with follow-up.", loc: "Gravesite Plain" },
        { id: 'blind', name: "Blind Spot (DLC)", type: 'Phys', desc: "Side dash stab. Ignores shields.", loc: "Gravesite Plain" },
        { id: 'swift', name: "Swift Slash (DLC)", type: 'Phys', desc: "Anime dash attack.", loc: "Hornsent Quest" },
        { id: 'roll', name: "Rolling Sparks (DLC)", type: 'Fire', desc: "Explosive perfume trail.", loc: "Shadow Keep" },
        { id: 'palm', name: "Palm Blast (DLC)", type: 'Phys', desc: "Chargeable palm strike.", loc: "Moorth Ruins" }
    ],
    talismans: [
        { id: 'shard', name: "Shard of Alexander", tag: 'skill', desc: "Boosts Skill damage by 15%.", loc: "Farum Azula (Alexander Quest)" }, 
        { id: 'blood', name: "Lord of Blood's Exultation", tag: 'bleed', desc: "Atk +20% when Bleed occurs.", loc: "Leyndell Catacombs" },
        { id: 'rot', name: "Kindred of Rot", tag: 'rot', desc: "Atk +20% when Poison/Rot occurs.", loc: "Seethewater Cave" }, 
        { id: 'claw', name: "Claw Talisman", tag: 'jump', desc: "Boosts Jump Attacks by 15%.", loc: "Stormveil Castle" },
        { id: 'curved', name: "Curved Sword Talisman", tag: 'guard', desc: "Boosts Guard Counters by 20%.", loc: "Stormveil Castle" }, 
        { id: 'axe', name: "Axe Talisman", tag: 'charge', desc: "Boosts Charged Attacks by 10%.", loc: "Mistwood Ruins" },
        { id: 'spear', name: "Spear Talisman", tag: 'counter', desc: "Boosts Counter Dmg (Pierce) by 15%.", loc: "Lakeside Crystal Cave" },
        { id: 'hammer', name: "Hammer Talisman", tag: 'stam', desc: "Increases stamina dmg against shields.", loc: "Limgrave (Recusant Henricus)" },
        { id: 'dagger', name: "Dagger Talisman", tag: 'crit', desc: "Boosts Critical Hits by 17%.", loc: "Volcano Manor" },
        { id: 'fire', name: "Fire Scorpion Charm", tag: 'fire', desc: "Fire Dmg +12%, Defense -10%.", loc: "Fort Laiedd" }, 
        { id: 'magic', name: "Magic Scorpion Charm", tag: 'magic', desc: "Magic Dmg +12%, Defense -10%.", loc: "Seluvis Questline" },
        { id: 'holy', name: "Sacred Scorpion Charm", tag: 'holy', desc: "Holy Dmg +12%, Defense -10%.", loc: "Anastasia Invader" }, 
        { id: 'light', name: "Lightning Scorpion Charm", tag: 'light', desc: "Lightning Dmg +12%, Defense -10%.", loc: "Wyndham Catacombs" },
        { id: 'rotten', name: "Rotten Winged Sword", tag: 'multi', desc: "Greatly boosts Atk on consecutive hits.", loc: "Millicent Questline" },
        { id: 'mill', name: "Millicent's Prosthesis", tag: 'multi', desc: "Boosts Atk on hits +5 DEX.", loc: "Millicent Questline (Alt)" },
        { id: 'godskin', name: "Godskin Swaddling Cloth", tag: 'heal', desc: "Heals HP on consecutive hits.", loc: "Spiritcaller Cave" },
        { id: 'ritual_s', name: "Ritual Sword Talisman", tag: 'fullhp', desc: "Atk +10% when HP is full.", loc: "Lux Ruins" },
        { id: 'ritual_d', name: "Ritual Shield Talisman", tag: 'fullhp', desc: "Def +30% when HP is full.", loc: "Leyndell Colosseum" },
        { id: 'red', name: "Red-Feathered Branchsword", tag: 'lowhp', desc: "Atk +20% when HP is low.", loc: "Deathbird (Liurnia)" },
        { id: 'blue', name: "Blue-Feathered Branchsword", tag: 'lowhp', desc: "Def +50% when HP is low.", loc: "Deathbird (Limgrave)" },
        { id: 'dragon', name: "Dragoncrest Greatshield", tag: 'def', desc: "Boosts Physical Negation by 20%.", loc: "Haligtree" },
        { id: 'pearl', name: "Pearldrake Talisman +2", tag: 'def', desc: "Boosts Non-Phys Negation.", loc: "Haligtree" },
        { id: 'turtle', name: "Green Turtle Talisman", tag: 'stam', desc: "Boosts Stamina Recovery speed.", loc: "Summonwater Village" },
        { id: 'amber_h', name: "Crimson Amber +2", tag: 'stat', desc: "Greatly boosts Max HP.", loc: "Leyndell Ashen Capital" },
        { id: 'amber_f', name: "Cerulean Amber +2", tag: 'stat', desc: "Greatly boosts Max FP.", loc: "Lunar Estate Ruins" },
        { id: 'amber_s', name: "Viridian Amber +2", tag: 'stat', desc: "Greatly boosts Max Stamina.", loc: "Miquella's Haligtree" },
        { id: 'favor', name: "Erdtree's Favor +2", tag: 'stat', desc: "Boosts HP, Stamina, and Equip Load.", loc: "Leyndell Ashen Capital" },
        { id: 'arsenal', name: "Great-Jar's Arsenal", tag: 'equip', desc: "Greatly boosts Equip Load.", loc: "Caelid Colosseum" },
        { id: 'rad_sore', name: "Radagon's Soreseal", tag: 'stat', desc: "+5 Vig/End/Str/Dex, but take more dmg.", loc: "Fort Faroth" },
        { id: 'mar_sore', name: "Marika's Soreseal", tag: 'stat', desc: "+5 Mind/Int/Fai/Arc, but take more dmg.", loc: "Elphael" },
        { id: 'bull', name: "Bull-Goat's Talisman", tag: 'poise', desc: "Boosts Poise by 33%.", loc: "Dragonbarrow Cave" },
        { id: 'godfrey', name: "Godfrey Icon", tag: 'charge', desc: "Boosts Charged Spells/Skills by 15%.", loc: "Golden Lineage Evergaol" },
        { id: 'rad_icon', name: "Radagon Icon", tag: 'cast', desc: "Shortens spell casting time.", loc: "Raya Lucaria Academy" },
        { id: 'flock', name: "Flock's Canvas Talisman", tag: 'incant', desc: "Greatly boosts Incantations.", loc: "Gowry Questline" },
        { id: 'graven', name: "Graven-Mass Talisman", tag: 'sorc', desc: "Greatly boosts Sorceries.", loc: "Albinauric Rise" },
        { id: 'old', name: "Old Lord's Talisman", tag: 'buff', desc: "Extends spell effect duration.", loc: "Farum Azula" },
        { id: 'carian', name: "Carian Filigreed Crest", tag: 'fp', desc: "Lowers Skill FP cost by 25%.", loc: "Iji (Carial Manor)" },
        { id: 'taker', name: "Taker's Cameo", tag: 'heal', desc: "Restores HP upon defeating enemies.", loc: "Volcano Manor Quest" },
        { id: 'ancestor', name: "Ancestral Spirit's Horn", tag: 'fp', desc: "Restores FP upon defeating enemies.", loc: "Regal Ancestor Spirit Rem." },
        { id: 'gold', name: "Gold Scarab", tag: 'farm', desc: "Increases Rune acquisition.", loc: "Abandoned Cave" },
        { id: 'silver', name: "Silver Scarab", tag: 'farm', desc: "Increases Item Discovery.", loc: "Hidden Path to Haligtree" },
        { id: 'crepus', name: "Crepus's Vial", tag: 'stealth', desc: "Eliminates all sound made by wearer.", loc: "Volcano Manor Quest" },
        { id: 'shabriri', name: "Shabriri's Woe", tag: 'aggro', desc: "Constantly attracts enemies' aggression.", loc: "Frenzy-Flaming Village" },
        { id: 'cat', name: "Longtail Cat Talisman", tag: 'util', desc: "Prevents fall damage (not death).", loc: "Raya Lucaria Academy" },
        { id: 'star_h', name: "Starscourge Heirloom", tag: 'stat', desc: "Raises STR by 5.", loc: "Fort Gael" },
        { id: 'pros_h', name: "Prosthesis-Wearer Heirloom", tag: 'stat', desc: "Raises DEX by 5.", loc: "Gowry Questline" },
        { id: 'gazer', name: "Stargazer Heirloom", tag: 'stat', desc: "Raises INT by 5.", loc: "Divine Tower of Liurnia" },
        { id: 'finger', name: "Two Fingers Heirloom", tag: 'stat', desc: "Raises FAI by 5.", loc: "Purified Ruins" },
        { id: 'blue_dance', name: "Blue Dancer Charm", tag: 'naked', desc: "Higher dmg with lower equip load.", loc: "Highroad Cave" },
        { id: 'crusade', name: "Crusade Insignia (DLC)", tag: 'heal', desc: "Boosts Atk after kill.", loc: "Belurat Tower" },
        { id: 'braid', name: "Golden Braid (DLC)", tag: 'def', desc: "Max Holy Negation.", loc: "Shaman Village" },
        { id: 'two_head', name: "Two-Headed Turtle (DLC)", tag: 'stam', desc: "Max Stamina Regen.", loc: "Rivermouth Cave" },
        { id: 'smith', name: "Smithing Talisman (DLC)", tag: 'throw', desc: "Boosts Throwing Weapons.", loc: "Ruined Forge" },
        { id: 'blade', name: "Blade of Mercy (DLC)", tag: 'crit', desc: "Boosts Atk after Crit.", loc: "Scorched Ruins" },
        { id: 'dried', name: "Dried Bouquet (DLC)", tag: 'sum', desc: "Boosts Atk when summon dies.", loc: "Belurat" },
        { id: 'enrage', name: "Enraged Divine Beast (DLC)", tag: 'storm', desc: "Boosts Storm Skills.", loc: "Lion Boss Reward" },
        { id: 'shat', name: "Shattered Stone (DLC)", tag: 'kick', desc: "Boosts Kicks/Stomps.", loc: "Moorth Ruins" }
    ],
    buffs: [
        { id: 'vow', name: "Golden Vow (Spell)", loc: "Corpse-Stench Shack, Mt Gelmir.", desc: "+15% Dmg, +10% Def (Body Buff)." },
        { id: 'fgms', name: "Flame, Grant Me Strength", loc: "Fort Gael, Caelid. Behind the fort.", desc: "+20% Phys/Fire Dmg (Body Buff)." },
        { id: 'terra', name: "Terra Magica", loc: "Academy Crystal Cave. After boss elevator.", desc: "+35% Magic Dmg zone." },
        { id: 'shab', name: "Howl of Shabriri", loc: "Frenzy-Flaming Tower, Liurnia.", desc: "+25% Dmg given, +30% Dmg taken." },
        { id: 'bloodflame', name: "Bloodflame Blade", loc: "Liurnia Lake. Teardrop Scarab.", desc: "Adds Blood/Fire to weapon." },
        { id: 'blackflame', name: "Black Flame's Protection", loc: "Roundtable Hold (Gideon).", desc: "+35% Phys Negation." },
        { id: 'electrify', name: "Electrify Armament", loc: "Artist's Shack, Liurnia.", desc: "Adds Lightning Dmg." },
        { id: 'order', name: "Order's Blade", loc: "Roundtable Hold (D).", desc: "Adds Holy Dmg. Kills Undead." },
        { id: 'poison_w', name: "Poison Armament", loc: "Aeonia Swamp, Caelid (Invisible Scarab).", desc: "Adds Poison Dmg." },
        { id: 'frozen', name: "Frozen Armament", loc: "Caria Manor (Scarab).", desc: "Adds Frostbite." },
        { id: 'scholars', name: "Scholar's Armament", loc: "Waypoint Ruins (Sellen).", desc: "Adds Magic Dmg." },
        { id: 'vyke_drag', name: "Vyke's Dragonbolt", loc: "Lord Contender's Evergaol.", desc: "Adds Lightning Dmg + Equip Load." },
        { id: 'protect', name: "Protection of the Erdtree", loc: "Altus Plateau (Scarab near Goldmask).", desc: "Boosts Holy Negation." },
        { id: 'barrier', name: "Barrier of Gold", loc: "Leyndell (Invisible Scarab).", desc: "Boosts Magic Negation." },
        { id: 'lord', name: "Lord's Divine Fortification", loc: "Roundtable Hold (Gideon).", desc: "Boosts Holy Negation (Massive)." },
        { id: 'flame_p', name: "Flame, Protect Me", loc: "Giant-Conquering Hero's Grave.", desc: "Boosts Fire Negation." }
    ],
    greases: [
        { id: 'fire', name: "Fire Grease" }, { id: 'magic', name: "Magic Grease" },
        { id: 'light', name: "Lightning Grease" }, { id: 'holy', name: "Holy Grease" },
        { id: 'blood', name: "Blood Grease" }, { id: 'freeze', name: "Freezing Grease" },
        { id: 'rot', name: "Rot Grease" }, { id: 'sleep', name: "Soporific Grease" },
        { id: 'poison', name: "Poison Grease" }, { id: 'dragon', name: "Dragonwound Grease" },
        { id: 'shield', name: "Shield Grease" }
    ],
    bosses: [
        { id: 'malenia', name: 'Malenia', weak: ['Fire', 'Bleed', 'Frost', 'Stagger'], resist: ['Holy', 'Rot'], tip: 'Weak to stagger. Use Frost Pots for Waterfowl.' },
        { id: 'radagon', name: 'Radagon', weak: ['Fire', 'Strike'], resist: ['Holy', 'Bleed'], tip: 'Immune to bleed. Strike damage works best.' },
        { id: 'elden', name: 'Elden Beast', weak: ['Physical'], resist: ['Holy', 'Status'], tip: 'Target the chest scar. Use Pest Threads or Black Flame.' },
        { id: 'mohg', name: 'Mohg', weak: ['Bleed'], resist: ['Fire'], tip: 'Purifying Crystal Tear is mandatory.' },
        { id: 'maliketh', name: 'Maliketh', weak: ['Physical'], resist: ['Holy'], tip: 'Low HP. Use Blasphemous Claw.' },
        { id: 'godskin', name: 'Godskin Duo', weak: ['Sleep', 'Bleed', 'Slash'], resist: ['Holy', 'Fire'], tip: 'Throw Sleep Pots to isolate 1v1.' },
        { id: 'rykard', name: 'Rykard', weak: ['Serpent'], resist: ['Fire'], tip: 'Must use Serpent-Hunter spear.' },
        { id: 'giant', name: 'Fire Giant', weak: ['Slash', 'Bleed'], resist: ['Fire'], tip: 'Attack the unarmored ankle, then hands.' },
        { id: 'placid', name: 'Placidusax', weak: ['Pierce'], resist: ['Status'], tip: 'Ancient Dragon. Use Pierce damage to tail.' },
        { id: 'tree', name: 'Draconic Tree Sentinel', weak: ['Strike', 'Rot'], resist: ['Lightning'], tip: 'Use Rotten Stray or Strike weapons.' },
        { id: 'messmer', name: 'Messmer (DLC)', weak: ['Bleed', 'Frost', 'Slash'], resist: ['Fire'], tip: 'Resists Fire. Punish snake attacks.' },
        { id: 'radahn_dlc', name: 'Consort Radahn (DLC)', weak: ['Pierce', 'Rot', 'Bleed'], resist: ['Holy', 'Slash'], tip: 'Use Greatshield + Poke weapon.' },
        // Extra Side Bosses
        { id: 'night', name: "Night's Cavalry", weak: ['Lightning', 'Strike'], resist: ['Slash'], tip: 'Knock off horse for instant crit.' },
        { id: 'bird', name: "Death Rite Bird", weak: ['Holy', 'Strike'], resist: ['Magic'], tip: 'Extremely weak to Holy Pots.' },
        { id: 'bell', name: "Bell Bearing Hunter", weak: ['Pierce', 'Lightning'], resist: ['Slash'], tip: 'Parry him. Do not heal far away.' },
        { id: 'watch', name: "Erdtree Watchdog", weak: ['Strike'], resist: ['Magic', 'Slash'], tip: 'Use Crystal Darts to glitch them.' },
        { id: 'garg', name: "Valiant Gargoyles", weak: ['Strike', 'Magic'], resist: ['Slash', 'Fire'], tip: 'Immune to status. Use Magic/Strike.' },
        { id: 'astel', name: "Astel, Naturalborn", weak: ['Physical'], resist: ['Magic', 'Elemental'], tip: 'Hit the head. Use Gravity stones.' },
        { id: 'rennala', name: "Rennala", weak: ['Physical', 'Bleed'], resist: ['Magic'], tip: 'Stagger her constantly.' },
        { id: 'ancestor', name: "Regal Ancestor Spirit", weak: ['Fire', 'Holy'], resist: ['Magic'], tip: 'Passive fight. Use Fire.' },
        { id: 'fortissax', name: "Lichdragon Fortissax", weak: ['Pierce'], resist: ['Lightning', 'Holy'], tip: 'Hit head/legs. Avoid death blight.' },
        { id: 'margit', name: "Margit/Morgott", weak: ['Slash', 'Bleed'], resist: ['Holy'], tip: 'Use Margit\'s Shackle.' }
    ],
    affinities: [
        { id: 'std', name: 'Standard', canBuff: true, desc: "Default scaling." }, { id: 'heavy', name: 'Heavy', canBuff: true, desc: "Str scaling." }, 
        { id: 'keen', name: 'Keen', canBuff: true, desc: "Dex scaling." }, { id: 'qual', name: 'Quality', canBuff: true, desc: "Str/Dex scaling." }, 
        { id: 'magic', name: 'Magic', type:'Magic', canBuff: false, desc: "Int scaling." }, { id: 'fire', name: 'Fire', type:'Fire', canBuff: false, desc: "Str scaling." },
        { id: 'flame', name: 'Flame Art', type:'Fire', canBuff: false, desc: "Fai scaling." }, { id: 'light', name: 'Lightning', type:'Lightning', canBuff: false, desc: "Dex scaling." },
        { id: 'sacred', name: 'Sacred', type:'Holy', canBuff: false, desc: "Fai scaling." }, { id: 'blood', name: 'Blood', type:'Phys', effect:'Bleed', canBuff: false, desc: "Arc scaling + Bleed." },
        { id: 'occult', name: 'Occult', type:'Phys', canBuff: false, desc: "Arc scaling." }, { id: 'cold', name: 'Cold', type:'Magic', effect:'Frost', canBuff: false, desc: "Int scaling + Frost." }
    ]
};
